### ISSUE TITLE
Change IP address?

### ISSUE THREAD

**Issue by GozuMezu** [wlcrs/huawei_solar#10]
### Describe your feature request

What should I do if a router reset changed my converter's ip address? Where can I adjust it?
Thanks for this amazing integration!

**Comment by wlcrs** [comment]
Please refer to the documentation of your router to check if it is possible to fix the IP-address that the DHCP server sets for your inverter.

For example, on OpenWRT routers this can be done like this: https://openwrt.org/docs/guide-user/luci/static_ip
