### ISSUE TITLE
What entities to use?

### ISSUE THREAD

**Issue by webdados** [wlcrs/huawei_solar#106]
I have a Huawei SUN 2000 + a Power Meter connected to it and I'm having difficulties understanding what entities to use on the Energy dashboard.

This is what I see on both devices:

<img width="674" alt="image" src="https://user-images.githubusercontent.com/6853605/182877315-3b9b3496-c8cb-4898-96cc-7fd9d3bf4026.png">

<img width="669" alt="image" src="https://user-images.githubusercontent.com/6853605/182877402-76036a30-3a75-48d4-b70d-6e1fa06fbcbe.png">

The energy dashboard requests entities in kWh, so for "Grid consumption" it seems that it's "Power meter Consumption" from the power meter, and for "Return to grid" it seems that it's "Power meter Exported" from the power meter also.

The problem is with "Solar production", as compared to the values I'm reading from Fusion Solar, it seems like it can only be "Active power" or "Input power" but those are not in kWh but in W, and of course, they do not show up on the options:

<img width="431" alt="image" src="https://user-images.githubusercontent.com/6853605/182878807-5c629347-c1f9-4ccb-a5d6-b6da9eefebfa.png">

Any hints?

**Comment by wlcrs** [comment]
HA will correctly deduce the Solar Production by selecting either "Inverter Daily yield" or "Inverter Total yield", as it does not use momentary values of the production (=W), but the summed values over longer times (=kWh). It therefore correctly suggests those two entities.

**Comment by bdkacz** [comment]
I recommend total yield - in my experience it causes fewer problems than daily
