### ISSUE TITLE
Receiving error when attempting to add integration with elevated permissions

### ISSUE THREAD

**Issue by BertisAU** [wlcrs/huawei_solar#109]
I am getting the error below when trying to add the integration with elevated permissions.
![Screenshot 2022-08-15 132706](https://user-images.githubusercontent.com/42926044/184581222-c199b68f-ca95-4b13-bb76-99da7ded1d7c.png)

**Comment by BertisAU** [comment]
![Screenshot 2022-08-15 131546](https://user-images.githubusercontent.com/42926044/184580828-35de3cd8-3c2e-4577-89f8-7bdc79a139a8.png)

**Comment by wlcrs** [comment]
Please describe your system: what inverter, what firmware version? Do you have optimizers? If so: which?

**Comment by BertisAU** [comment]
I have two Huawei inverters but they are not connected to each other. I have tried to add the integration to both of them and receive the same error.

SUN2000-10KTL-M2 running on version V100R001C00SPC141
SUN2000-5KTL-M1 running on version V100R001C00SPC141

Optimisers model is SUN2000-450W-P

There are (26) optimisers connected to the 10kW inverter and (13) optimisers  connected to the 5kW inverter . 

All optimisers are on version V100R002C10SPC002.

**Comment by wlcrs** [comment]
What version of the integration are you using? The line numbers in your error message are of, and it's getting me confused.

When using the latest version, this error should not occur as I check the size of the package before trying to process it:

```
        # Check if we have an empty file
        if len(file_data) < struct.calcsize(OptimizerRealTimeDataFile.HEADER):
            return

        self.file_version = struct.unpack_from(
            OptimizerRealTimeDataFile.HEADER, file_data, offset
        )


```

**Comment by BertisAU** [comment]
I just tried to add the integration again and it's installed correctly for the 10kW. I'm really not sure what has changed but I'm happy it's working now.
![Screenshot 2022-08-16 160633](https://user-images.githubusercontent.com/42926044/184829925-84246891-a242-4ad8-a90e-9489c5ea46c7.png)
