### ISSUE TITLE
[Feature Request]:  Document how to use Force Charge/Discharge Mode

### ISSUE THREAD

**Issue by dklemm** [wlcrs/huawei_solar#110]
### Describe your feature request

Setting the "Force Charge Power" does not change the force charge mode.

Please can you describe how "Force Charge/Discharge Mode" can be using from this integration.

<img width="344" alt="Screenshot 2022-08-15 at 22 31 47" src="https://user-images.githubusercontent.com/2111972/184722182-530ca788-3da6-4e70-a2d1-32c3715f37e2.png">

Mode not changed :

<img width="1129" alt="Screenshot 2022-08-15 at 22 27 57" src="https://user-images.githubusercontent.com/2111972/184724988-b386fcf1-d02b-4e0e-9927-f6cb5de4a407.png">

Manually changed in the battery config page:

<img width="1053" alt="Screenshot 2022-08-15 at 22 55 24" src="https://user-images.githubusercontent.com/2111972/184725109-4eec79db-4cda-44d3-9cf3-6e08d056f6e8.png">

**Comment by wlcrs** [comment]
Is this clear enough? 

https://github.com/wlcrs/huawei_solar/wiki/Force-charge-discharge-battery

**Comment by dklemm** [comment]
Thats perfect, I didn't even know about the services.

I think there is some overlap with config, I wonder if it make sense to make these readonly entites/attrs.  

It would also be good to to try and report the force charge/discharge state and remaning time/soc in the entities.

FWIW my system allowed me to set the power to 5000w (2x2500w battries) but there is some other limit of 3000w that prevented it from charging.  I'll give the services a try to see if they report a fail in the same setup.  I think the config should be limited to the lowest but I'm still trying to figure out where this limit comes from.

I will do some more testing and raise and Issues/Feature Req if I find anything

**Comment by sadiq81** [comment]
@dklemm how did you make that card.
