### ISSUE TITLE
[Bug]: Inverter changed IP

### ISSUE THREAD

**Issue by marithpl** [wlcrs/huawei_solar#128]
### System Health details

Connection problem

### Huawei Solar Setup

SDongle 

### Describe the issue

I've today problem with router. I had to reset factory settings.
Now Dongle have different IP, how to change it without loosing data.
And I don't know what was original address.

Is it possible to view configuration address IP ?

### Relevant debug logs

```text
n/d
```

**Comment by wlcrs** [comment]
This is not a bug, and it's bad practice to allow dynamic IP assignment for something like this. You need to set a fixed IP for your dongle instead.

**Comment by marithpl** [comment]
I always use IP reservation.
I didn't found option to set static ip for inverter.

**Comment by marithpl** [comment]
But I found a solution.
In HA config folder there is hidden folder .storage with core.config_entries.

Everything seems to work

**Comment by kaciker** [comment]
> But I found a solution. In HA config folder there is hidden folder .storage with core.config_entries.
> 
> Everything seems to work

Thanks ¡ you saved my live..
