### ISSUE TITLE
[Feature Request]: SDongle Register 37500 for Load Power

### ISSUE THREAD

**Issue by HansPeterMeier** [wlcrs/huawei_solar#136]
### Describe your feature request

Is it possible to add some register from the SDongle?
I want the address 37500 and 37502
The unit id must be set to 100. 
With my node red flow this works already

Thanks for you add on :-)

![image](https://user-images.githubusercontent.com/32676715/190131357-d8609284-f785-40c3-8c8e-072a13556b63.png)

### Proper usage

- [X] I confirm that this is not a bug report

**Comment by wlcrs** [comment]
I don't see great value in supporting these registers as their values can be deducted from entities that are already exported by the integration.

Furthermore: As I don't own an SDongle this is difficult for me to implement and test. 

You are welcome to contribute pull requests here and in the underlying library to add support yourself.
