### ISSUE TITLE
[Bug]: Trying to call the select service wo luck

### ISSUE THREAD

**Issue by kristianolofsson** [wlcrs/huawei_solar#139]
### System Health details

-

### Huawei Solar Setup

-

### Describe the issue

Trying to automate changing the selector switch for battery mode wo any luck. How to call that type of service?
Tried below wo any luck
service: select.select_option
data:
  option: Fully Feed To Grid
target:
  entity_id: select.battery_working_mode

### Relevant debug logs

```text
-
```

**Comment by wlcrs** [comment]
I don't do free support. Please only use the issue tracker for bugs.
