### ISSUE TITLE
[Feature Request]: Make daily yield sensor not counting battery discharge

### ISSUE THREAD

**Issue by barksten** [wlcrs/huawei_solar#155]
### Describe your feature request

I'm not sure if it's a bug or not but the thing is:
Sensor _Daily inverter yield_ seems to be based on _Inverter Active Power_ instead of _Inverter Input Power_.
This results in battery discharge increases the daily yield and messes up the energy graphs.

### Proper usage

- [X] I confirm that this is not a bug report

**Comment by wlcrs** [comment]
Duplicate of #1

**Comment by barksten** [comment]
Sorry! My bad! Thanks for pointing this out.
