### ISSUE TITLE
[Feature Request]: How to add monthly yield?

### ISSUE THREAD

**Issue by MariuszWoszczynski** [wlcrs/huawei_solar#157]
### Describe your feature request

How to add monthly yield in sensor.py?

### Proper usage

- [X] I confirm that this is not a bug report

**Comment by wlcrs** [comment]
Use https://www.home-assistant.io/integrations/utility_meter/

The issue tracker is not a support forum. Please use other more appropriate channels instead (for example the Discussions tab).
