### ISSUE TITLE
[Feature Request]: maximize selfconsumption AND charge from grid during offpeak on demand

### ISSUE THREAD

**Issue by chrishuette** [wlcrs/huawei_solar#170]
### Describe your feature request

During summer we have enough energy from the PV to power our house during day and night. But in fall and winter there are days when the energy is insufficient to last the whole day and when the next day is cloudy the production is even to small to cover the day. We have cheap electricity from the grid between 22:00 and 6:00. So it would be great to charge the battery at this time, when Battery is already low or the forecast for the next day is low. toggle between maximum selfconsumpion and TOU (time of use) would be great. 👍  thanks for your amazing work!

### Proper usage

- [X] I confirm that this is not a bug report

**Comment by wlcrs** [comment]
This is out of scope for this integration. You can create HA automations to manipulate the battery parameters that fit your use case.
