### ISSUE TITLE
[Feature Request]: migration from old plugin emilv2

### ISSUE THREAD

**Issue by WMP** [wlcrs/huawei_solar#175]
### Describe your feature request

Hello, year ago I use plugin from Emilv2 repository and I migrate to your huawei_solar version. In graphs I don't see old data. Is possible to convert old data to your plugin?

### Proper usage

- [X] I confirm that this is not a bug report

**Comment by wlcrs** [comment]
No. That is not supported by Home Assistant.

**Comment by WMP** [comment]
But data migration in database is possible?

**Comment by wlcrs** [comment]
Possibly, but not officially documented and certainly not officially supported

**Comment by WMP** [comment]
Maybe this is hint: https://community.home-assistant.io/t/migrate-energy-statistics-from-one-entity-to-another/405863/7

I will try and give you feedback

**Comment by wlcrs** [comment]
Always welcome to create a Wiki entry with clear instructions on how to do
the migration!
