### ISSUE TITLE
[Bug]: Minor cosmetic "bug"

### ISSUE THREAD

**Issue by jvcsw** [wlcrs/huawei_solar#189]
### Describe the issue

Hi everyone,

first of all, thank you very much for your work.

The sensor "battery_state_of_capacity" has one decimal, but this decimal always is 0.
Could you change this float value to a integer value?

Normally, these percentages do not have decimals.

Thanks

### Bescribe your Huawei Solar Setup

Inverter Type:
Inverter Firmware version:
SDongle present: yes / no
Power meter present: three phase / single phase / no
Battery: LG RESU xxkWh / LUNA2000 xxkWh / None
Battery Firmware version:

### How do you connect to the inverter?

Via the `SUN2000-<serial_no>` WiFi

### Upload your Diagnostics File

Drag & Drop your Diagnostics File here.

### Upload your relevant debug logs

```text
without logs
```

### Please confirm the following:

- [X] The problem is still present in the latest release of this integration.
- [ ] I did not find an existing issue describing this problem.
- [ ] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [ ] I increased the logging configuration, restarted HA, and have copied all relevant log lines from the 'Full Logs' into the textarea.

**Comment by wlcrs** [comment]
The Modbus register for the SoC reports this with a 'gain' of 10. This means that when this register contains 250, the SoC is 25.0% .
It is thus perfectly technically possible that the inverter starts reporting the SoC in more detail. For example with a register value of 333, meaning a SoC of 33.3%.

Therefore, it doesn't seem like a good idea to force it to a round value.
