### ISSUE TITLE
[Feature Request]: Retrieve MPPT DC cumulative energy values from the inverter 

### ISSUE THREAD

**Issue by RabAusten** [wlcrs/huawei_solar#197]
### Describe your feature request

I would like to know exactly how much power has been generated by my array, as DC input to the inverter. Using the existing Yield figures adds complexity as it also includes power generated by my battery.

I noticed that the FusionSolar app allows you to view _Historical info_ under Devices > Inverter > Historical info

If I select:
- Signal type = Yield (kWh)
- Signal point =  MPPT 1 DC cumulative energy (kWh) + MPPT 2 cumulative energy (kWh)

I can then sum the values given at 00:00 and subtract them from the sum of values at 23:59 the same day. This gives the total DC input energy for the day.

(See screenshots below)

Would it be possible to expose these values for MPPT 1 and MPPT 2 for each inverter, so they can be templated together?

Thanks
James

![Screenshot_20221130-195947~2](https://user-images.githubusercontent.com/508069/204899007-d1ca5147-b6ec-4ff2-acad-31c1b6c0506e.png)
![Screenshot_20221130-195952~2](https://user-images.githubusercontent.com/508069/204899000-f2f8b9a4-0914-4724-b8d3-345fa4473c65.png)

### Proper usage

- [X] I confirm that this is not a bug report

**Comment by wlcrs** [comment]
This integration enables you to see the information that the inverter exposes over Modbus. All relevant fields related to yield are already exported into HA. This is not one of them.
