### ISSUE TITLE
[Bug]: initialisation problem after power failure

### ISSUE THREAD

**Issue by gilder0** [wlcrs/huawei_solar#198]
### Describe the issue

Hi, 

I encouter problem with initialisation of entities after power failure.  
When electricity came back, home assistant starts faster than inverter, and initialization of entities failed with exception:

[...]python3.9/site-packages/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File [...]/huawei_solar/__init__.py", line 166, in async_setup_entry
    raise err
  File [...]/huawei_solar/__init__.py", line 63, in async_setup_entry
    primary_bridge = await HuaweiSolarBridge.create(
  File [...]/python3.9/site-packages/huawei_solar/bridge.py", line 80, in create
    await HuaweiSolarBridge.__populate_fields(bridge)
  File [...]/python3.9/site-packages/huawei_solar/bridge.py", line 156, in __populate_fields
    await bridge.client.get(
  File [...]/python3.9/site-packages/huawei_solar/huawei_solar.py", line 254, in get
    return (await self.get_multiple([name], slave))[0]
  File [...]/python3.9/site-packages/huawei_solar/huawei_solar.py", line 304, in get_multiple
    result = [await self._decode_response(registers[0], decoder)]
  File [...]/python3.9/site-packages/huawei_solar/huawei_solar.py", line 246, in _decode_response
    result = reg.decode(decoder, self)
  File [...]/python3.9/site-packages/huawei_solar/registers.py", line 78, in decode
    result = self.unit(result)
  File [...]/enum.py", line 360, in __call__
    return cls.__new__(cls, value)
  File [...]/python3.9/enum.py", line 677, in __new__
    raise ve_exc

I think i this situation also should be thrown ConfigEntryNotReady exception, as home assistant could retry after a while

### Bescribe your Huawei Solar Setup

Inverter Type:
Inverter Firmware version:
SDongle present: yes / no
Power meter present: three phase / single phase / no
Battery: LG RESU xxkWh / LUNA2000 xxkWh / None
Battery Firmware version:

### How do you connect to the inverter?

Via the SDongle, wireless connection

### Upload your Diagnostics File

Drag & Drop your Diagnostics File here.

### Upload your relevant debug logs

```text
[...]python3.9/site-packages/homeassistant/config_entries.py", line 357, in async_setup
result = await component.async_setup_entry(hass, self)
File [...]/huawei_solar/init.py", line 166, in async_setup_entry
raise err
File [...]/huawei_solar/init.py", line 63, in async_setup_entry
primary_bridge = await HuaweiSolarBridge.create(
File [...]/python3.9/site-packages/huawei_solar/bridge.py", line 80, in create
await HuaweiSolarBridge.__populate_fields(bridge)
File [...]/python3.9/site-packages/huawei_solar/bridge.py", line 156, in __populate_fields
await bridge.client.get(
File [...]/python3.9/site-packages/huawei_solar/huawei_solar.py", line 254, in get
return (await self.get_multiple([name], slave))[0]
File [...]/python3.9/site-packages/huawei_solar/huawei_solar.py", line 304, in get_multiple
result = [await self._decode_response(registers[0], decoder)]
File [...]/python3.9/site-packages/huawei_solar/huawei_solar.py", line 246, in _decode_response
result = reg.decode(decoder, self)
File [...]/python3.9/site-packages/huawei_solar/registers.py", line 78, in decode
result = self.unit(result)
File [...]/enum.py", line 360, in call
return cls.new(cls, value)
File [...]/python3.9/enum.py", line 677, in new
raise ve_exc
```

### Please confirm the following:

- [ ] The problem is still present in the latest release of this integration.
- [ ] I did not find an existing issue describing this problem.
- [ ] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [ ] I increased the logging configuration, restarted HA, and have copied all relevant log lines from the 'Full Logs' into the textarea.

**Comment by wlcrs** [comment]
Fixed in 1.2.0 beta 5
