### ISSUE TITLE
Add huawei logo's to hacs integration

### ISSUE THREAD

**Issue by Vato9394** [wlcrs/huawei_solar#2]
Add huawei logo's to the repository @ https://github.com/home-assistant/brands
So that the logo is present on the integration page.
![huawei solar integration](https://user-images.githubusercontent.com/24278426/138588224-e7a5bafd-097e-4bfb-9593-7955e5c6780a.png)

**Comment by wlcrs** [comment]
Done: https://github.com/home-assistant/brands/pull/2928
