### ISSUE TITLE
[Feature Request]: Add restart options

### ISSUE THREAD

**Issue by asern1989** [wlcrs/huawei_solar#200]
### Describe your feature request

Please add restart inverter option to HA
THX

### Proper usage

- [X] I confirm that this is not a bug report

**Comment by wlcrs** [comment]
As there is no documented way to perform a restart of the inverter via Modbus, I cannot add this feature.

**Comment by asern1989** [comment]
![image](https://user-images.githubusercontent.com/9203289/205486369-a4feb2a1-3851-480f-955e-b105eb1a82b6.png)

**Comment by wlcrs** [comment]
The smartlogger is not the inverter. It's an optional component mainly used in big installations with multiple inverters. It's not even supported by this integration for the moment. (cfr #93)
