### ISSUE TITLE
[Bug]: Efficiency sensor unknown when 0 production

### ISSUE THREAD

**Issue by Fettkeewl** [wlcrs/huawei_solar#239]
### Describe the issue

Efficiency sensor becomes unknown when there is no solar production.
Persistent across HA reboot. Breaks any cards dependent on it. 0 Production should yield efficiency sensor value 0
![image](https://user-images.githubusercontent.com/25577040/210799716-51499a7d-4d35-4501-9437-061f05ee09bc.png)

### Bescribe your Huawei Solar Setup

Inverter Type: SUN2000-5KTL-M1GIN300-5KTL-M1
Inverter Firmware version:  V100R001C00SPC148
SDongle present: yes 
Power meter present: three phase 
Battery:  None

### How do you connect to the inverter?

Via the SDongle, wireless connection

### Upload your Diagnostics File

[config_entry-huawei_solar-3f729813c0c94972af1799bfd4bbe978.json.txt](https://github.com/wlcrs/huawei_solar/files/10352778/config_entry-huawei_solar-3f729813c0c94972af1799bfd4bbe978.json.txt)

### Upload your relevant debug logs

```text
not applicable
```

### Please confirm the following:

- [X] The problem is still present in the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [X] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [X] I increased the logging configuration, restarted HA, and have copied all relevant log lines from the 'Full Logs' into the textarea.

**Comment by wlcrs** [comment]
Not a bug: the inverter reports 'no value' in that case.
