### ISSUE TITLE
[Bug]: Got a warning in the logs after upgrade to HA 2.23.1.0

### ISSUE THREAD

**Issue by billerby** [wlcrs/huawei_solar#242]
### Describe the issue

Warning message after upgrade of HA.

I am running the latest beta version (1.2.0 beta 7) of the integration.

`Entity sensor.power_meter_power_factor (<class 'custom_components.huawei_solar.sensor.HuaweiSolarSensorEntity'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('power_factor') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.`

### Bescribe your Huawei Solar Setup

Inverter Type: SUN2000-10KTL-M1 
Inverter Firmware version: V100R001C00SPC148
SDongle present: yes
Power meter present: three phase
Battery: LUNA2000 15kWh / None
Battery Firmware version: V100R002C00SPC116

### How do you connect to the inverter?

Via the SDongle, wireless connection

### Upload your Diagnostics File

Drag & Drop your Diagnostics File here.
[config_entry-huawei_solar-3adb58081624dc046af7e2a8c487877a.json(1).txt](https://github.com/wlcrs/huawei_solar/files/10355634/config_entry-huawei_solar-3adb58081624dc046af7e2a8c487877a.json.1.txt)

### Upload your relevant debug logs

```text
2023-01-05 22:10:26.539 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.power_meter_power_factor (<class 'custom_components.huawei_solar.sensor.HuaweiSolarSensorEntity'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('power_factor') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
2023-01-05 22:13:48.480 INFO (MainThread) [backoff] Backing off _do_read(...) for 1.0s (asyncio.exceptions.TimeoutError)
```

### Please confirm the following:

- [X] The problem is still present in the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [X] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [x] I increased the logging configuration, restarted HA, and have copied all relevant log lines from the 'Full Logs' into the textarea.

**Comment by wlcrs** [comment]
Thank you for the bugreport. I tackled the changes mentioned on https://developers.home-assistant.io/blog/2022/12/05/more-unit-enumerators while at it. 

This will be fixed in the next version.
