### ISSUE TITLE
[Feature Request]: Faster switching of Grid Charge On/Off

### ISSUE THREAD

**Issue by CommanderROR9** [wlcrs/huawei_solar#270]
### Describe your feature request

Hi,

With my Setup (Sun2000 8TKL M1, Luna2000 10kWh) and connection via Modbus/TCP to the Sdongle I get a delay of pretty much exactly 10 Minutes when I use the "Charge from Grid" switch. This makes using it for automations pretty difficult, because I need to add a 10 Minute wait after using the "Charge from Grid" switch.

Can this be changed somehow?

### Proper usage

- [X] I confirm that this is not a bug report

**Comment by wlcrs** [comment]
This is not a feature request. Please fill in the bug report template with steps to reproduce, including debug logs generated as described here: https://www.home-assistant.io/docs/configuration/troubleshooting/#debug-logs-and-diagnostics

Now I have no clue what version of the integration you are using, what you mean by the 10 minute delay, etc.

**Comment by CommanderROR9** [comment]
I am sorry, but this is not a bug AFAIK. There are no errors, nothing in
the logs, it simply takes exactly 10 Minutes for the switch "Charge from
Grid" to actually enable or disable the Charge from Grid function.
But if you insist I can try and go through the procedure of creating a bug
report if that helps...

Am So., 22. Jan. 2023 um 16:22 Uhr schrieb Thijs W. <
***@***.***>:
