### ISSUE TITLE
Battery End-of-discharge SOC valid range is set to 12 - 20, instead of 0-20

### ISSUE THREAD

**Issue by raulliive** [wlcrs/huawei_solar#277]
### Describe the issue

End-of-Discharge SOC valid range is currently set to 12-20%, while Huawei allows in Fusion Solar it to be set to as low as 0.

I believe this integration should follow Huawei's configuration options.

Please change the number.py line 83 to allow end of discharge to be set to 0.

### Bescribe your Huawei Solar Setup

Inverter Type:
Inverter Firmware version:
SDongle present: yes / no
Power meter present: three phase / single phase / no
Battery: LG RESU xxkWh / LUNA2000 xxkWh / None
Battery Firmware version:

### How do you connect to the inverter?

Via the SDongle, wired connection

### Upload your Diagnostics File

Drag & Drop your Diagnostics File here.

### Upload your relevant debug logs

```text
Not relevant.
```

### Please confirm the following:

- [X] The problem is still present in the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [ ] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [ ] I increased the logging configuration, restarted HA, and have copied all relevant log lines from the 'Full Logs' into the textarea.

**Comment by wlcrs** [comment]
Strangely enough, the Huawei Solar Modbus Interface Definitions tell me that the valid value range for that register is `[12, 20]`:

![image](https://user-images.githubusercontent.com/2150060/215333154-3d776a19-5f4b-411e-b91d-53b8e1662032.png)
