### ISSUE TITLE
Inversor Yield Today entity 

### ISSUE THREAD

**Issue by Tomaxote** [wlcrs/huawei_solar#287]
### Describe your feature request

Fusion solar has the "Inversor Yield Today" entity, but itn´t in the integration. 

### Proper usage

- [X] I confirm that this is not a bug report

**Comment by wlcrs** [comment]
It's not exposed by the inverter via modbus

**Comment by jfbuggen** [comment]
Hi @wlcrs could you reach me via pm, I would like to share with you some info/experiences on modbus registers. Thanks!
