### ISSUE TITLE
[Feature Request]: Slave ID = 1 when using the dongle

### ISSUE THREAD

**Issue by luotinen** [wlcrs/huawei_solar#291]
### Describe your feature request

Can you change this:
"Enter the IP address and port on which the Modbus-TCP interface is available (when connecting to the inverter AP the host IP is typically 192.168.200.1 and the port is either 502 or 6607). The slave id is typically 0. You should only check the Advanced: elevate permissions checkbox if you intend to dynamically change your inverter and battery settings, or want access to the optimizer data."

Into:
"Enter the IP address and port on which the Modbus-TCP interface is available (when connecting to the inverter AP the host IP is typically 192.168.200.1 and the port is either 502 or 6607). The slave id is typically 0. **Set slave id to 1 if using a wifi dongle.** You should only check the Advanced: elevate permissions checkbox if you intend to dynamically change your inverter and battery settings, or want access to the optimizer data."

### Proper usage

- [X] I confirm that this is not a bug report

**Comment by tomderidder** [comment]
That would not fit for all users I guess. For example, I connect to a wifi-dongle, and I need to use slave id 0
