### ISSUE TITLE
[Feature Request]: Battery status entity

### ISSUE THREAD

**Issue by joaovitoriasilva** [wlcrs/huawei_solar#31]
### Describe your feature request

Hello,

Is it possible to have a entity to give the battery status, like running, stand by, etc?

Thank you.

**Comment by wlcrs** [comment]
I'll include a sensor for the following register in the next release:

```
  rn.STORAGE_RUNNING_STATUS: U16Register(rv.StorageStatus, 1, 37762, 1),
```

```
class StorageStatus(IntEnum):
    """Status of the attached energy storage."""

    OFFLINE = 0
    STANDBY = 1
    RUNNING = 2
    FAULT = 3
    SLEEP_MODE = 4
```

**Comment by joaovitoriasilva** [comment]
Awesome! Thank you. 🙂

**Comment by VederJay** [comment]
Seems to be working now, thanks!

**Comment by wlcrs** [comment]
I still need to fix the values so that they are better "human readable".
I'll keep this issue open for now until that is fixed

**Comment by wlcrs** [comment]
Has been improved in 1.0.1
