### ISSUE TITLE
[Feature Request]: Split sensor.battery_charge_discharge_power

### ISSUE THREAD

**Issue by P-Stenbumling** [wlcrs/huawei_solar#317]
### Describe your feature request

Would it be possible to split sensor.battery_charge_discharge_power into one charge and one discharge?
perhaps possible to solve with a template sensor otherwise?

### Proper usage

- [X] I confirm that this is not a bug report
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by wlcrs** [comment]
Not within scope
