### ISSUE TITLE
[Bug]: daily yield wrong value

### ISSUE THREAD

**Issue by ikxdf** [wlcrs/huawei_solar#329]
### Describe the issue

daily yield sensor show power consumption. This bug is present at last version of inverter firmware and last version of integration. before last version the sensor works correctly.

the daily yeld sensor is reporting the daily consumption now. Data is identically at power consumption on solar fusion app.

<img width="691" alt="image" src="https://user-images.githubusercontent.com/18067289/226169549-bd1d5861-978c-4637-98f8-e165a6daf5a5.png">

### Bescribe your Huawei Solar Setup

Inverter Type: SUN2000-6KTL-L1
Inverter Firmware version: V200R001C00SPC130
SDongle present:  no
Power meter present: single phase 
Battery: LUNA2000 30kWh 
Battery Firmware version: V200R001C00SPC130

### How do you connect to the inverter?

Via the `SUN2000-<serial_no>` WiFi

### Upload your Diagnostics File

Drag & Drop your Diagnostics File here.

### Upload your relevant debug logs

```text
no logs,
check image
```

### Please confirm the following:

- [X] The problem is still present in the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [X] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [X] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by wlcrs** [comment]
This integration does not interpret the values returned by the inverter. It just passes them on to HA.
