### ISSUE TITLE
Daily Yield also counts battery usage

### ISSUE THREAD

**Issue by thomasnas** [wlcrs/huawei_solar#34]
Hi,

First of all, thanks for the great work on this integration, we use it daily in our HA setup ! 

In our house, we have a solar installation with also a 10Kwh battery installed.
I noticed that the Daily Yield also includes the battery discharge value.
You can clearly see this when the sun is down, then the Daily Yield is still increasing.

I was wondering if there is no other value that can be read to just have the PV Yield and not have the battery usage included ?

Thanks

**Comment by wlcrs** [comment]
The inverter does not expose such a value. CFR #1
