### ISSUE TITLE
[Feature Request]: update the firmware on the inventor & battery

### ISSUE THREAD

**Issue by kurtdefeyter** [wlcrs/huawei_solar#341]
### Describe your feature request

Is it technically possible when you signed in as installer to read & update the firmware ?

### Proper usage

- [X] I confirm that this is not a bug report
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by wlcrs** [comment]
This is not documented in the modbus definitions.

**Comment by kurtdefeyter** [comment]
thank for for this very quick response ....Geniet nog een beetje van U zondag man
