### ISSUE TITLE
[Feature Request]: live monitoring.

### ISSUE THREAD

**Issue by BaDTaG** [wlcrs/huawei_solar#350]
### Describe your feature request

am was tryg to integrate it to HA using nordpole plugin so i culd get a live (per 1 houer view) of power used, sold, battery charge and discharge.

but it only shows daily as selectable in nordpole plugin

SDongleA-05 - network kabel
SUN2000-10KTL-M1
LUNA2000 10kw
smart meter

### Proper usage

- [X] I confirm that this is not a bug report
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by Kimfamous** [comment]
Perhaps I'm misunderstanding what you're asking, but you can derive that information using HomeAssistant's existing Utility Meter function from this integration's total increasing sensors (eg sensor.power_meter_consumption, sensor.power_meter_exported, sensor.battery_total_charge and sensor.total_battery_discharge).
