### ISSUE TITLE
[Bug]: Wrong value in Power Meter Consumption

### ISSUE THREAD

**Issue by NiFu90** [wlcrs/huawei_solar#372]
### Describe the issue

I am using this integration since around 2 weeks and enjoying it.
But browsing around I saw the value of Power Meter Consumption (registry GRID_ACCUMULATED_ENERGY), which I think is the house consumption with electricity from the grid, to be 514 kWh while FusionSolar App and also my physical official energy counter in my house show something around 98 kWh which is definitely more realistic.
Either I misunderstood the meaning of the entity or the value is wrong.

Interestingly, the exported energy is on point and in line with the other two sources.

### Bescribe your Huawei Solar Setup

Inverter Type: SUN2000-10KTL-M1
Inverter Firmware version: V100R001C00SPC153
SDongle present: yes
Power meter present: three phase
Battery: LUNA2000 10kWh
Battery Firmware version:

### How do you connect to the inverter?

Over serial, with a serial-to-USB stick

### Upload your Diagnostics File

[config_entry-huawei_solar-e555e9fe5df0969ac7c14f9216b9891c.json.txt](https://github.com/wlcrs/huawei_solar/files/11442188/config_entry-huawei_solar-e555e9fe5df0969ac7c14f9216b9891c.json.txt)
[home-assistant_huawei_solar_2023-05-10T13-26-03.554Z.log](https://github.com/wlcrs/huawei_solar/files/11442334/home-assistant_huawei_solar_2023-05-10T13-26-03.554Z.log)

### Upload your relevant debug logs

```text
Added the debug log in the diagnostics input because upload was not possible in this field.
```

### Please confirm the following:

- [X] The problem is still present in the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [X] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [X] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by wlcrs** [comment]
Please use the latest beta version to gather additional debug logs: the beta version collects more information that I can use to diagnose the issue.

**Comment by NiFu90** [comment]
[config_entry-huawei_solar-e555e9fe5df0969ac7c14f9216b9891c.json(1).txt](https://github.com/wlcrs/huawei_solar/files/11476337/config_entry-huawei_solar-e555e9fe5df0969ac7c14f9216b9891c.json.1.txt)

**Comment by jires** [comment]
@NiFu90 take a look on smart meter physical display, what shows there. If total on smart meter display is identical with data in HA, so is nothing wrong with integration. Fusionsolar shows only usage from grid while system is connected (inverter is on ). If you have smart meter installed before inverter was started up, will those values mismatch..

**Comment by NiFu90** [comment]
Hey @jires thanks for the Feedback. I had a look at the smart meter and indeed it is showing the value that I see in the integration, so you are right, the meter also shows the “wrong” value. But I got it installed together with the rest of the system. Is it possible the meter had a non-zero value already when installed? But as I said the exported energy value checks out perfectly, only the grid consumption is too high, as far as I can see (don’t have database history yet) the accumulation is correct now. Seems it has an offset. Thanks for your opinion
