### ISSUE TITLE
Optimizers data

### ISSUE THREAD

**Issue by drejc12** [wlcrs/huawei_solar#375]
### Describe the issue

In which format is it possible to get per optimizer data?
Is it like timestamp, optimizer identification (like SN) and power? If I am not wrong, optimizer data is on 5min time intervals, right?

### Bescribe your Huawei Solar Setup

Inverter Type: SUN2000-10KTL-M1
Inverter Firmware version: 153
SDongle present: yes
Power meter present: three phase
Battery: None

### How do you connect to the inverter?

Via the SDongle, wired connection

### Upload your Diagnostics File

Drag & Drop your Diagnostics File here.

### Upload your relevant debug logs

```text
Not a bug, just a question.
```

### Please confirm the following:

- [ ] The problem is still present in the latest release of this integration.
- [ ] I did not find an existing issue describing this problem.
- [ ] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [ ] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by wlcrs** [comment]
This is an issue tracker. Not a free support channel
