### ISSUE TITLE
cannot get get connectivity between HA on my home network and the inverter AP

### ISSUE THREAD

**Issue by frigo99** [wlcrs/huawei_solar#40]
Hello,

first of all thanks for your great work and detailed descriptions!
I was trying to make connection, integration of Huawei Solar feature to my HA based on raspberry pi4.
I tried: following procedure: configure this device in Hass.io via Configuration -> Add-ons, Backups & Supervisor -> System -> Change (next to IP address) -> WLAN<x>. 
Inverter was found as wifi AP. but i cannot manage to connect.  Error message received:
"Failed to change network settings
Activating connection failed, check connection settings."

Please support/guide how to continue in order to get connections.

Thank you!

![issue](https://user-images.githubusercontent.com/102687079/161319047-18e5d5c8-cb61-42ce-b533-465a3a8ef0dc.jpg)
P

**Comment by wlcrs** [comment]
I don't have any experience with this setup, so I can't help you. Please use the community resources of Home Assistant to get support for this issue.
