### ISSUE TITLE
Inverter is forgetting Parallel communication mode

### ISSUE THREAD

**Issue by viandham** [wlcrs/huawei_solar#43]
Hey guys. I fully realize this is not a problem with this HA integration, but I figure this would be the best way to reach out to users that might have had similar issues.

I have a SUN2000 10kW inverter with smart dongle, but I have a problem accessing it. I can enable the modbus tcp communication, but when setting the parallel communication mode to RS485 it remembers it until the app is closed, next time it is always set to NA. It does not seem to set the setting at all, only displays it as set in the app until next restart.

Have anyone encountered this before?

I want to use the smart dongle to access modbus that way, the internal wifi of the inverter seems to have very low range and I am unable to move more than a few meters away from it. It is also outside so the signal is very dodgy (mostly non-existent) from where my HA server is.

Any ideas and help would be appreciated.

**Comment by malteger** [comment]
I am also unable to change this option, the app says it is set, but it apparently is not. The inverter (model SUN2000-6KTL-M1) is on firmware version `V100R001C00SPC141`, the dongle on `V100R001C00SPC127`.

@wlcrs Am I correct that this version needs the "Parallel communication mode": "RS485" option? I am currently using the version by Emilv2, which works somehow. As there is work done to get this one into HA core I tried to switch, but can't get it to work. If that is not necessary I will debug further on the HA side

**Comment by wlcrs** [comment]
This integration uses Emilv2's library as it's basis. I've made some improvements along the way, but in essence: if Emilv2's integration worked for you, this one should work as well.

My theory about the parallel communication mode is that this is only necessary if you use the RS485_1 pins of the communication cable to connect to the inverter. The integration currently only supports using these pins via a serial-to-tcp bridge, which I know works for at least one user.

**Comment by viandham** [comment]
I have an open case with Huawei Inverter Support for this issue.
Previously I have not gotten the integration to talk to my system, but I haven't tried in a week or so. However, I tried right now - and it worked. No idea why.
So I still have the issue with the RS485 and the app, but it does communicate now. Which it refused to do before. Don't know why, but I guess I'm happy? :D

**Comment by malteger** [comment]
I can also confirm that it works well without the setting, my problem was something else.

**Comment by viandham** [comment]
@wlcrs You can close this issue, I have gotten what I needed to get things working. Thank you for the help and great work with huawei_solar!

**Comment by viandham** [comment]
Apparently I can close it myself. Thank you.
