### ISSUE TITLE
[Bug]: HA Services, multiple with same name

### ISSUE THREAD

**Issue by ThomDietrich** [wlcrs/huawei_solar#431]
### Describe the issue

Hello, check the screenshot below. As you can see, three services are described by "Huawei Solar: Set Active Power Control to Unlimited mode", which I suspect is not intended.

![image](https://github.com/wlcrs/huawei_solar/assets/2870104/493113ff-c60d-473e-96e0-0710f9d9a92d)

### Bescribe your Huawei Solar Setup

Inverter Type: SUN2000-10KTL-M1-HC
Inverter Firmware version: latest
SDongle present: no
Power meter present: no
Battery: None
Battery Firmware version:

### How do you connect to the inverter?

Over serial, with a serial-to-WiFi stick

### Upload your Diagnostics File

[config_entry-huawei_solar-f61543400e1b6c1346d3dd0813ab9633.json.txt](https://github.com/wlcrs/huawei_solar/files/12171659/config_entry-huawei_solar-f61543400e1b6c1346d3dd0813ab9633.json.txt)

### Upload your relevant debug logs

```text
I hope no logs are required for this issue. Very happy to provide all the log data needed to resolve this issue though.
```

### Please confirm the following:

- [X] The problem is still present in the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [X] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [X] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by ThomDietrich** [comment]
Btw not fixed in 1.2.7b1

**Comment by wlcrs** [comment]
Already fixed: https://github.com/wlcrs/huawei_solar/commit/1b39063e9e37395d278332bd63ad6cf77d084d21#diff-476759a1d4ca0225d35e990ad3c57a4a2d5193563a9b764dee3044c6aeecfc0c

**Comment by ThomDietrich** [comment]
Maybe I need to restart the system for this to take effect. Thanks!!
