### ISSUE TITLE
[Bug?]: Data sometimes not valid

### ISSUE THREAD

**Issue by t0bse** [wlcrs/huawei_solar#435]
### Describe the issue

i am runnig this integration for a while now, since a few days we got bad weather here in germany, so sometimes i have the sun changing in one minute for a few times.

now i noticed, that the sensors are wrong sometimes. (i think it's only happening if the clouds are coming/going) 

see screenshots, all values have the same timestamp.

may also be a huawei problem? it seems like the values are not saved at the same second, one of the both values seems to be a few seconds older, sometimes.

inverter_active_power:
![image](https://github.com/wlcrs/huawei_solar/assets/45834518/3bd867bf-61d6-483e-8843-7897215f3503)

power_meter_active_power:
![image](https://github.com/wlcrs/huawei_solar/assets/45834518/c885b212-0267-4c67-98d6-65de2bd3d411)

my sensor calculates "inverter minus power_meter active power" and so it says
![image](https://github.com/wlcrs/huawei_solar/assets/45834518/bd37cfc7-746a-4d59-a114-ec76bb8d3d1e)

i can also see this the other way:
inverter_active_power:
![image](https://github.com/wlcrs/huawei_solar/assets/45834518/f7bdf191-53fb-446f-8d21-a5427a4657d7)
power_meter_active_power:
![image](https://github.com/wlcrs/huawei_solar/assets/45834518/f5dbfce2-9571-4980-a040-a0b52daf8555)
so my sensor:
![image](https://github.com/wlcrs/huawei_solar/assets/45834518/8642c8bd-29b3-4df8-8daf-174c1a2363fe)

### Bescribe your Huawei Solar Setup

Inverter Type: SUN2000-10KTL-M0
Inverter Firmware version: V100R001C00SPC153
SDongle present: yes 
Power meter present: three phase 
Battery: None
Battery Firmware version:

### How do you connect to the inverter?

Via the SDongle, wired connection

**Comment by jires** [comment]
I'm experiencing same issues.
I have figured out, that sometimes Integration has problems to read all registers and retrying. Those registers which are not read at the first time, cannot be updated together with others registers on pooling time, so there can be 2 options. Either they will be "unavailable" until they get new reading, or they will keep current value. Thankfully to newly changes, they keeping current value. Unfortunately, it can be a situation, where different registers values are "shifted" in time for some seconds, therefore is mismatch in values when they changing very fast.

I think this is good trade off, what we get from integration and what inverter/usb dongle is capable of deliver. 
Only way to avoid this is to turn off completely all those registers which are not used/ not essentials, and make less load on Modbus module in the inverter.

**Comment by wlcrs** [comment]
Thank you @jires for the fine explanation.

This integration just exposes what it can read from the inverter. I batch-read as much as possible to get consistent values. If the values that you see are strange, it is the fault of the inverter, not of the integration.
