### ISSUE TITLE
[Feature Request]: Quicker entity update via service call

### ISSUE THREAD

**Issue by ThomDietrich** [wlcrs/huawei_solar#438]
### Describe your feature request

Hey there,
thanks for your integration! My setup: SUN2000-10KTL-M1-HC via Protoss PE11-H.

As documented in your README, the integration retrieved values periodically every 30 seconds. That's generally fine but I need a few values more frequently.

After a bit of testing I have questions, and the hope that we can either improve current functionality or the README.

1. Why can't I go below a polling rate of 10 seconds? Is that a limitation of the inverter itself?
1. Is there a way to define an automation for ALL entities, rather than specifying individual entity_ids (e.g. When I want all secondary entities to update every 60s)?
1. It seems like all entities are updated when I define the entity_update automation for a single huawei_solar entity. Is that a bug?
1. Coming back to question 1: If the inverter registers are updated only every 10 seconds, does the integration ensure that data is read upon update, or might readings be up to 9 seconds delayed?

Context: I want to synchronize the reading of values from the inverter and different smart meters and consumers, to have an accurate point-in-time view on power and energy flows.

### Proper usage

- [X] I confirm that this is not a bug report or support request
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by wlcrs** [comment]
This is a bug tracker, not a support channel

**Comment by ThomDietrich** [comment]
Hey, you might be mistaken. 

1. is a feature request,
2. is a feature request,
3. is a bug report,
4. is a question, agreed.

Please have a look at number 3 at least. Thanks you

**Comment by cgernert** [comment]
As far as I know, this is because of the SDongle
https://skyboo.net/2022/02/huawei-sun2000-why-using-a-usb-dongle-for-monitoring-is-not-a-good-idea/
