### ISSUE TITLE
[Bug]: HA Core Update 2023.8.2 breaks integration

### ISSUE THREAD

**Issue by mckrabben** [wlcrs/huawei_solar#445]
### Describe the issue

I updated to core version of 2023.8.2 and the integration stopped working after some hours. 

Now I restored to a backup and everything works again perfectly, which leads me to the conclusion that the latest core update breaks something.

My connection directly with the hotspot to my 5ktl inverter still worked, but the one connected over internet “failed to initialize “

### Bescribe your Huawei Solar Setup

Inverter Type: Sun2000 5ktl and sun2000 10 ktl
Inverter Firmware version: V100R001C00SPC153
SDongle present: yes
Power meter present: three phase
Battery: LUNA2000 10kWh
Battery Firmware version: shows blank in FusionSolar, but it’s recently been updated 

### How do you connect to the inverter?

Via the SDongle, wired connection

### Upload your Diagnostics File

I restored to a backup so I don’t have the diagnostics, unfortunately.

### Upload your relevant debug logs

```text
I restored from a backup so I don’t have them.
```

### Please confirm the following:

- [X] The problem is still present in the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [ ] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [ ] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by wlcrs** [comment]
no logs = nothing for me to debug
