### ISSUE TITLE
read battery  SOH level [Feature Request]: 

### ISSUE THREAD

**Issue by kurtdefeyter** [wlcrs/huawei_solar#477]
### Describe your feature request

would it be possible to read the soh level.
according the information i found on the forum it should be in 

37004 - 1 register - unsigned integer - 1 decimal (so you have to divide by 10 to get the % value) 

best regards

kurt

### Proper usage

- [X] I confirm that this is not a bug report or support request
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by wlcrs** [comment]
This integration needs to strike a balance between performance and completeness. This register cannot be added to the batch reads already being done by the integration, and I will therefore not implement it as it would further slow down each update cycle.

You can add it yourself following these instructions: https://github.com/wlcrs/huawei_solar/wiki/Defining-custom-sensors
