### ISSUE TITLE
[Feature Request]: Allow change update interval

### ISSUE THREAD

**Issue by inigoml** [wlcrs/huawei_solar#48]
### Describe your feature request

Method for modifying update interval for sensors is not working and if it works, it's not very usable since you have to update two dozen of sensors. Exposing a property at integration level as a parameter in order to change update interval should be preferred way. I've manually modified code at const.py and it's working properly but, of course, a more easy way is desirable.

Justification: (changing update interval has a good reason).

After upgrade SPC115 in SUN2000-KTL-L1 and disabling direct query to SUN2000 inverter via regular wifi (not commissioning WIFI), some weird behavior is present. Now a network gateway between commissioning wifi and regular wifi is a must and modbus tcp query must be done via commissioning wifi. If you query very frequently inverter, at a given moment, it stops sending data to Huawei servers and FusionSolar app stop receiving data. This flow is restored as soon as you stop integration or restart HA. Some bug at inverter side locks sending information to Huawei when querying via modbus TCP. As I said, only with SPC115 and later. Modbus keeps running. Only affect to Huawei sending process.
This lock happens once or twice per day, sometimes a bit longer, but always before 48 hours. I've tested by modifying query interval to 150 seconds and no problem has arisen for 72 hours.

**Comment by wlcrs** [comment]
I will not implement this, as this would hinder adoption as a core integration into HA.

I'm not happy about this either, but this would just increase the maintenance cost for me on this library.
