### ISSUE TITLE
[Feature Request]: Integration with OpenAPI

### ISSUE THREAD

**Issue by mbertaboni** [wlcrs/huawei_solar#50]
### Describe your feature request

Hello, 
Given the fact that not everyone can or wants to connect directly in ModBUS to the inverter, I was wondering why not integrate directly the part of OpenAPI that Huawei provides.
In my case, I am not the installer of the system nor do I want to be, but I do want to be able to read the data via API. All I had to do was ask Huawei for an OpenAPI account and I am in possession of all the data that can be obtained using ModBUS (I think so.. see https://trengo.s3.eu-central-1.amazonaws.com/media/2y5JxXaS8cGn6o06_smartpvms-v500r007c00-northbound-interface-reference.pdf) .
Unfortunately my knowledge on how to develop a home assistant component is very poor, but here on GitHub there is someone who is doing a similar work to yours starting from the API (https://github.com/jgriss/FusionSolarHA/). 
It would be nice to collaborate and create a single component that can either connect directly via modbus or use the API.
I find that using the API is much less invasive (in the end you just have to ask for credentials and the installer has no problem), different is connecting directly to the inverter via modbus (maybe interrupting or getting in the way of the installer).
This is obviously just an idea/request.

Thanks in advance, great work !

**Comment by wlcrs** [comment]
This is not within the scope of this integration. This could be a completely separate integration instead.

I'm not interested in implementing this OpenAPI integration due to the aggressive rate limiting and delay of the values being reported.
