### ISSUE TITLE
Unable to set battery working mode through the REST API

### ISSUE THREAD

**Issue by stefaanv** [wlcrs/huawei_solar#537]
### Describe the issue

Changing the `battery_working_mode` configuration over the REST API doesn't work.
The API does reflect the new state back, but the working mode hasn't changed in reality.
After the api call, the drop-down list in the lovelace interface for the `battery working mode` configuration is empty.

![image](https://github.com/wlcrs/huawei_solar/assets/18347072/79b0d9bb-4cf2-4f08-b850-c16fbd416479)

I'm using these calls :
**POST** to `http://homeassistant.local:8123/api/states/select.battery_working_mode`
body
```json
{
  "state": "Maximise Self Consumption"
}
```
returns
```json
{
  "entity_id": "select.battery_working_mode",
  "state": "Maximise Self Consumption",
  "attributes": {},
  "last_changed": "2023-11-08T17:02:42.497145+00:00",
  "last_updated": "2023-11-08T17:02:42.497145+00:00",
  "context": {
    "id": "01...9P",
    "parent_id": null,
    "user_id": "dca...32"
  }
}
```
**GET** to `http://homeassistant.local:8123/api/states/select.battery_working_mode`
returns
```json
{
  "entity_id": "select.battery_working_mode",
  "state": "Maximise Self Consumption",
  "attributes": {},
  "last_changed": "2023-11-08T17:02:42.497145+00:00",
  "last_updated": "2023-11-08T17:02:42.497145+00:00",
  "context": {
    "id": "01...T9P",
    "parent_id": null,
    "user_id": "dca...b32"
  }
}
```

### Bescribe your Huawei Solar Setup

Inverter Type: SUN2000-4.6KTL-L1
Inverter Firmware version:V200R001C00SPC130
SDongle present: yes / no
Power meter present:  single phase 
Battery: LUNA2000 10kWh 

### How do you connect to the inverter?

TCP/IP to modbus converter furthr connected to the inverter over rs485

### Upload your Diagnostics File

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.11.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Brussels",
    "os_name": "Linux",
    "os_version": "6.1.21-v8",
    "supervisor": "2023.11.0",
    "host_os": "Home Assistant OS 11.1",
    "docker_version": "24.0.6",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "huawei_solar": {
      "version": "1.2.7",
      "requirements": [
        "huawei-solar==2.2.9"
      ]
    },
    "hacs": {
      "version": "1.33.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "huawei_solar",
    "name": "Huawei Solar",
    "config_flow": true,
    "documentation": "https://github.com/wlcrs/huawei_solar/wiki",
    "issue_tracker": "https://github.com/wlcrs/huawei_solar/issues",
    "requirements": [
      "huawei-solar==2.2.9"
    ],
    "codeowners": [
      "@wlcrs"
    ],
    "iot_class": "local_polling",
    "version": "1.2.7",
    "loggers": [
      "huawei_solar",
      "pymodbus"
    ],
    "is_built_in": false
  },
  "data": {
    "config_entry_data": {
      "host": "192.168.0.7",
      "port": 502,
      "slave_ids": [
        1
      ],
      "enable_parameter_configuration": true,
      "username": null,
      "password": null
    },
    "slave_0": {
      "model_name": "SUN2000-4.6KTL-L1",
      "pv_string_count": 2,
      "has_optimizers": 0,
      "battery_type": 2,
      "battery_1_type": 2,
      "battery_2_type": 0,
      "power_meter_type": 0,
      "supports_capacity_control": true
    },
    "slave_0_data": {
      "input_power": [
        0,
        "W"
      ],
      "line_voltage_A_B": [
        232.6,
        "V"
      ],
      "line_voltage_B_C": [
        0.0,
        "V"
      ],
      "line_voltage_C_A": [
        0.0,
        "V"
      ],
      "phase_A_voltage": [
        240.8,
        "V"
      ],
      "phase_B_voltage": [
        0.4,
        "V"
      ],
      "phase_C_voltage": [
        0.0,
        "V"
      ],
      "phase_A_current": [
        3.134,
        "A"
      ],
      "phase_B_current": [
        0.0,
        "A"
      ],
      "phase_C_current": [
        0.0,
        "A"
      ],
      "day_active_power_peak": [
        4848,
        "W"
      ],
      "active_power": [
        723,
        "W"
      ],
      "reactive_power": [
        1,
        "VA"
      ],
      "power_factor": [
        1.0,
        null
      ],
      "grid_frequency": [
        50.0,
        "Hz"
      ],
      "efficiency": [
        100.0,
        "%"
      ],
      "internal_temperature": [
        24.9,
        "\u00b0C"
      ],
      "insulation_resistance": [
        30.0,
        "MOhm"
      ],
      "device_status": [
        "On-grid",
        null
      ],
      "fault_code": [
        0,
        null
      ],
      "startup_time": [
        "2023-11-08T07:38:21+00:00",
        null
      ],
      "shutdown_time": [
        null,
        null
      ],
      "accumulated_yield_energy": [
        13840.69,
        "kWh"
      ],
      "daily_yield_energy": [
        5.94,
        "kWh"
      ],
      "state_1": [
        [
          "Grid-Connected",
          "Grid-Connected normally"
        ],
        null
      ],
      "state_2": [
        [
          "Unlocked",
          "PV disconnected",
          "DSP data collection"
        ],
        null
      ],
      "state_3": [
        [
          "On-grid",
          "Off-grid switch disabled"
        ],
        null
      ],
      "alarm_1": [
        [],
        null
      ],
      "alarm_2": [
        [],
        null
      ],
      "alarm_3": [
        [],
        null
      ],
      "pv_01_voltage": [
        0.0,
        "V"
      ],
      "pv_01_current": [
        0.0,
        "A"
      ],
      "pv_02_voltage": [
        0.0,
        "V"
      ],
      "pv_02_current": [
        0.0,
        "A"
      ],
      "meter_status": [
        1,
        null
      ],
      "grid_A_voltage": [
        232.3,
        "V"
      ],
      "grid_B_voltage": [
        null,
        "V"
      ],
      "grid_C_voltage": [
        null,
        "V"
      ],
      "active_grid_A_current": [
        -0.61,
        "I"
      ],
      "active_grid_B_current": [
        null,
        "I"
      ],
      "active_grid_C_current": [
        null,
        "I"
      ],
      "power_meter_active_power": [
        0,
        "W"
      ],
      "power_meter_reactive_power": [
        141,
        "Var"
      ],
      "active_grid_power_factor": [
        -0.057,
        null
      ],
      "active_grid_frequency": [
        49.99,
        "Hz"
      ],
      "grid_exported_energy": [
        4825.18,
        "kWh"
      ],
      "grid_accumulated_energy": [
        3679.98,
        "kWh"
      ],
      "grid_accumulated_reactive_power": [
        0.0,
        "kVarh"
      ],
      "meter_type": [
        0,
        null
      ],
      "active_grid_A_B_voltage": [
        null,
        "V"
      ],
      "active_grid_B_C_voltage": [
        null,
        "V"
      ],
      "active_grid_C_A_voltage": [
        null,
        "V"
      ],
      "active_grid_A_power": [
        null,
        "W"
      ],
      "active_grid_B_power": [
        null,
        "W"
      ],
      "active_grid_C_power": [
        null,
        "W"
      ],
      "storage_state_of_capacity": [
        23.0,
        "%"
      ],
      "storage_running_status": [
        2,
        null
      ],
      "storage_bus_voltage": [
        439.0,
        "V"
      ],
      "storage_bus_current": [
        -1.7,
        "A"
      ],
      "storage_charge_discharge_power": [
        -723,
        "W"
      ],
      "storage_total_charge": [
        5188.01,
        "kWh"
      ],
      "storage_total_discharge": [
        5024.12,
        "kWh"
      ],
      "storage_current_day_charge_capacity": [
        6.3,
        "kWh"
      ],
      "storage_current_day_discharge_capacity": [
        5.59,
        "kWh"
      ]
    },
    "slave_0_config_data": {
      "storage_maximum_charging_power": [
        5000,
        "W"
      ],
      "storage_maximum_discharging_power": [
        5000,
        "W"
      ],
      "storage_charging_cutoff_capacity": [
        100.0,
        "%"
      ],
      "storage_discharging_cutoff_capacity": [
        10.0,
        "%"
      ],
      "storage_working_mode_settings": [
        5,
        null
      ],
      "storage_charge_from_grid_function": [
        true,
        null
      ],
      "storage_grid_charge_cutoff_state_of_charge": [
        100.0,
        "%"
      ],
      "storage_fixed_charging_and_discharging_periods": [
        [
          {
            "__type": "<class 'huawei_solar.registers.ChargeDischargePeriod'>",
            "repr": "ChargeDischargePeriod(start_time=480, end_time=600, power=-1500)"
          },
          {
            "__type": "<class 'huawei_solar.registers.ChargeDischargePeriod'>",
            "repr": "ChargeDischargePeriod(start_time=600, end_time=960, power=2000)"
          },
          {
            "__type": "<class 'huawei_solar.registers.ChargeDischargePeriod'>",
            "repr": "ChargeDischargePeriod(start_time=960, end_time=1320, power=-1500)"
          }
        ],
        null
      ],
      "storage_power_of_charge_from_grid": [
        3000,
        "W"
      ],
      "storage_maximum_power_of_charge_from_grid": [
        3000,
        "W"
      ],
      "storage_time_of_use_charging_and_discharging_periods": [
        [
          {
            "__type": "<class 'huawei_solar.registers.HUAWEI_LUNA2000_TimeOfUsePeriod'>",
            "repr": "HUAWEI_LUNA2000_TimeOfUsePeriod(start_time=841, end_time=960, charge_flag=<ChargeFlag.CHARGE: 0>, days_effective=(False, False, False, False, False, False, True))"
          }
        ],
        null
      ],
      "storage_excess_pv_energy_use_in_tou": [
        1,
        null
      ],
      "storage_backup_power_state_of_charge": [
        0.0,
        "%"
      ],
      "storage_capacity_control_mode": [
        0,
        null
      ],
      "storage_capacity_control_soc_peak_shaving": [
        50.0,
        "%"
      ],
      "storage_capacity_control_periods": [
        [],
        null
      ]
    }
  }
}

### Upload your relevant debug logs

```text
Logger: custom_components.huawei_solar
Source: helpers/update_coordinator.py:322
Integration: Huawei Solar (documentation, issues)
First occurred: 7 november 2023 om 22:11:37 (23 occurrences)
Last logged: 17:32:51

Error fetching HV20C0137463_data_update_coordinator data: Could not update HV20C0137463 values: Got error while reading from register 32064 with length 52: Exception Response(131, 3, GatewayNoResponse)
Error fetching HV20C0137463_configuration_update_coordinator data: Could not update HV20C0137463 values: Got error while reading from register 47075 with length 14: Exception Response(131, 3, GatewayNoResponse)
Error fetching HV20C0137463_data_update_coordinator data: Could not update HV20C0137463 values: Got error while reading from register 37760 with length 28: Exception Response(131, 3, GatewayNoResponse)
```

### Please confirm the following:

- [X] The problem is still present in the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [X] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [X] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by wlcrs** [comment]
Please read the INFO-box in the documentation of HA:

![image](https://github.com/wlcrs/huawei_solar/assets/2150060/0b1fa40e-7588-48ce-b413-8cdab28c24e4)

**Comment by stefaanv** [comment]
Then how can I set the Battery WorkingMode ?
Which is the correct URL/post data to change it?  It is  a state, so it should be possible to change.
Changing it in Developer Tools changes the state but that change isn't written to the inverter according to the Huawei app.
