### ISSUE TITLE
[Feature Request]: negative Max. grid feed-in power (kW): -0.020 kW

### ISSUE THREAD

**Issue by MayBankCH** [wlcrs/huawei_solar#544]
### Describe your feature request

[Feature Request]: negative Max. grid feed-in power (kW): -0.020 kW
API error when input negative Max. grid feed-in power.

![image](https://github.com/wlcrs/huawei_solar/assets/82813803/a2de9706-1f04-445f-9c31-61f40690ebfd)
![image](https://github.com/wlcrs/huawei_solar/assets/82813803/df45c325-1184-4edc-86b1-36bdc1e2b7d2)
Max. grid feed-in power >=0 is ok.

### Proper usage

- [X] I confirm that this is not a bug report or support request
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by MayBankCH** [comment]
I create another power check script for negative Max. grid feed-in power. 
![image](https://github.com/wlcrs/huawei_solar/assets/82813803/2c1edf98-eb08-4133-b15c-25df42af5a32)
![image](https://github.com/wlcrs/huawei_solar/assets/82813803/338731e3-d28b-45b0-ade0-76313feae26b)

**Comment by Roving-Ronin** [comment]
Also wondering why the maximum to feed into the grid is 5kW, if this is implemented at the sDongle+Consumption meter level (as opposed to the limit at the individual inverter level), this stops users with multiple/cascaded inverters from being able to choose a combined limit that is greater than a single inverter.

i.e. 2 x 6kW inverters, capable of 13.2kW Active Power between them, and being able to limit export to grid to say 10kW.

**Comment by wlcrs** [comment]
The minimum value that you can enter is already set to -1000. The integration does not enforce a maximum.

Cfr. https://github.com/wlcrs/huawei_solar/blob/bbf441d3ec508fcad0c3434925b69c33855508b0/services.py#L118

**Comment by MayBankCH** [comment]
Noted with thanks. BTW -1000 is -1000 W or -1000 kW

**Comment by MayBankCH** [comment]
The minimun value is set to -1000. 
However, power call "_validate_power_value" function 
then check assert Power>=0 and 0 <=Power <= Max

![image](https://github.com/wlcrs/huawei_solar/assets/82813803/33dfcc62-0a68-418d-9c53-d86e48dd4b0f)

![image](https://github.com/wlcrs/huawei_solar/assets/82813803/48c04698-a7a9-40b5-924c-d7462a47806e)

![image](https://github.com/wlcrs/huawei_solar/assets/82813803/fd776e6d-ac11-4d0f-ac7d-56d6c7fc4ecb)
