### ISSUE TITLE
[Feature Request]: Battery Charge Grid at Specific Datime

### ISSUE THREAD

**Issue by bbday** [wlcrs/huawei_solar#548]
### Describe your feature request

Should be good if possible setup dynamicly when charge battery from grid only by specific datetime.
Example i would like refill battery only by 5:00 to 7:00 other timinig charge from grid should be switch off.

I dont think is hard to implement it just change option at specific time. no idea if can be perform by HA by it self without need to edit plugin code.

### Proper usage

- [X] I confirm that this is not a bug report or support request
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by dragorex71** [comment]
It is already possible.
You have to set up with Fusion Solar app the periods of charging you like. It is mandatory even if you decide to not charge in that period.
Aftyer that via Home Assistant with ad automation you can change "select.battery_working_mode" from "Maximise self consumption" to "Time of Use" at the same time you have set before. If you don't change the working mode it does not charge even if you have set a period of charge
