### ISSUE TITLE
Forced charge/discharge with services? 

### ISSUE THREAD

**Issue by Tabbe70** [wlcrs/huawei_solar#55]
Hi,
I have installed the integration via HACS and it works well.
It is possible to use the services in Automations?
As I cant get this to work, I guess that there is some limitations when it is possible to run Forced charge/discharge? More than the obvious cases that you cant charge when battery has SOC 100%. 

Can this for example be done in combination with "Max self Consumtion" or only with "Time of Use". 

I plan to set this up with the state of an binary sensor that gives states "on" /"off" depending on Nordpool prices and level of SOC in battery
/TB

**Comment by wlcrs** [comment]
Yes the services should work, and are being used by others. I'm not sure what more I can say if you don't provide more information? The bug report template exists for a reason...
