### ISSUE TITLE
[Feature Request]: LUNA ESS - Add State of Health (SoH) Sensors

### ISSUE THREAD

**Issue by Roving-Ronin** [wlcrs/huawei_solar#552]
### Describe your feature request

Hi WLCRS,

To allow tracking the 'State of Health' (SoH) of the LUNA battery (overall) and the individual battery packs, so that visibility is provided as to the status and gradual decline of the batteries, thereby allowing alerting and tracking this status. Short term this would allow seeing if actions are adversely affecting the SoH (i.e. grid arbitrage) and longer term allowing monitoring of this SoH and flagging issues if the number of cycles (effective full cycles) and corresponding SoH breaches the 60% guaranteed SoW under warranty.

Looking at the modbus registers and these appear to be registers 37920 (Battery 1 / Pack 1 - SoH Calibration Status), that then repeats for Pack 2-3 and then Battery 2 Pack 1,2 & 3) with the final register being 37926 that is " SoH Calibration Status", that would appear to be the over battery(ies) status.

Many Thanks for Consideration.

### Proper usage

- [X] I confirm that this is not a bug report or support request
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by wlcrs** [comment]
The more registers that are being read by this integration, the slower this integration becomes. Update timeouts are already a problem for a segment of users of this integration, especially when multiple inverters are installed.

I thus need to strike a balance between usability and stability of this integration. This integration currently only reads registers that hold aggregated numbers of all installed battery packs. All of these registers can be read in one operation, providing good performance. I don't think it is a good idea to add any specific battery (pack) registers, as this would greatly increase the number of registers to be read: one inverter can have two batteries of each 3 packs. So reading the SOH or battery temperature could mean up to 6 additional registers being read.

I've provided instructions on the Wiki on how to add extra sensors yourself: https://github.com/wlcrs/huawei_solar/wiki/Defining-custom-sensors
