### ISSUE TITLE
[Feature Request]: Batterietemperatur hinzufügen

### ISSUE THREAD

**Issue by schmersgahoven** [wlcrs/huawei_solar#555]
### Describe your feature request

Es wäre gut, wenn die Temperatur der Batterie über die Schnittstelle abgegriffen und angezeigt werden könnte. Gerade in unbeheizten Räumlichkeiten spielt die Temperatur eine wichtige Rolle.
Danke 

### Proper usage

- [X] I confirm that this is not a bug report or support request
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by seeker1973** [comment]
Wurde hier schon einmal gefragt und beantwortet:
https://github.com/wlcrs/huawei_solar/issues/541
Ansonsten bekommt man hier, wenn nicht auf englisch gefragt, keine Antworten.
