### ISSUE TITLE
[Bug]: Grid exported

### ISSUE THREAD

**Issue by kristianolofsson** [wlcrs/huawei_solar#56]
### System Health details

-

### Huawei Solar Setup

SUN2000 6KTL, Dongle 

### Describe the issue

Can only see 25 entities and Grid exported is not one of them. What did i do wrong?

### Reproduction steps

1.
2.
3.
...

### Relevant debug logs

```text
-
```

**Comment by wlcrs** [comment]
Please fill in the bug report, list which entities you  do see.

**Comment by kristianolofsson** [comment]
sensor.a_b_line_voltage
sensor.a_b_line_voltage
sensor.active_power
sensor.b_c_line_voltage
sensor.b_c_line_voltage
sensor.c_a_line_voltage
sensor.c_a_line_voltage
sensor.daily_yield
sensor.day_active_power_peak
sensor.device_status
sensor.efficiency
sensor.input_power
sensor.internal_temperature
sensor.internal_temperature
sensor.phase_a_current
sensor.phase_a_current
sensor.phase_a_voltage
sensor.phase_a_voltage
sensor.phase_b_current
sensor.phase_b_current
sensor.phase_b_voltage
sensor.phase_b_voltage
sensor.phase_c_current
sensor.phase_c_current
sensor.phase_c_voltage
sensor.phase_c_voltage
sensor.power_factor
sensor.power_factor
sensor.pv_1_current
sensor.pv_1_voltage
sensor.pv_2_current
sensor.pv_2_voltage
sensor.reactive_power
sensor.reactive_power
sensor.shutdown_time
sensor.startup_time
sensor.total_yield

**Comment by wlcrs** [comment]
Grid sensors are only available if you have a power meter connected.
