### ISSUE TITLE
[Feature Request]: Manually set the battery between sleep mode and running

### ISSUE THREAD

**Issue by LotharWoman** [wlcrs/huawei_solar#569]
### Describe your feature request

Is it possible to install a switch to change the battery between sleep mode and running? 
 The whole thing is useful with variable electricity tariffs, as the unused battery has very high consumption in the "running" status. This would make it possible to charge at night, then put the battery into sleep mode during the day and back to running in the evening.

![Unbenannt 1](https://github.com/wlcrs/huawei_solar/assets/124817112/5bd747e4-d06b-41fd-9038-8129600d9906)

### Proper usage

- [X] I confirm that this is not a bug report or support request
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by wlcrs** [comment]
No, this is a read only modbus address (cfr third column in your screenshot)
