### ISSUE TITLE
[Bug]: message about using deprecated constants in code since HA 2024.2

### ISSUE THREAD

**Issue by Fossy777** [wlcrs/huawei_solar#583]
### Describe the issue

ENERGY_KILO_WATT_HOUR was used from huawei_solar, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please create a bug report at https://github.com/wlcrs/huawei_solar/issues
POWER_WATT was used from huawei_solar, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.WATT instead, please create a bug report at https://github.com/wlcrs/huawei_solar/issues

### Bescribe your Huawei Solar Setup

not relevant in this

### How do you connect to the inverter?

Via the SDongle, wireless connection

### Upload your Diagnostics File

Drag & Drop your Diagnostics File here.
[config_entry-huawei_solar-11bd3ab901a0a52c4b6897c80babb854.json.txt](https://github.com/wlcrs/huawei_solar/files/13827547/config_entry-huawei_solar-11bd3ab901a0a52c4b6897c80babb854.json.txt)

### Upload your relevant debug logs

```text
n.rel.
```

### Please confirm the following:

- [X] The problem is still present in the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [X] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [ ] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by wlcrs** [comment]
Already fixed in #577 . Keeping this issue open until I do a release to prevent more people from opening a duplicate issue.
