### ISSUE TITLE
After SW V200R001C00SPC121 no longer able to connect in either 502 or 6607

### ISSUE THREAD

**Issue by andrema2** [wlcrs/huawei_solar#59]
## System Health

version | core-2022.5.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.108
arch | x86_64
timezone | America/Sao_Paulo

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4895
Installed Version | 1.24.5
Stage | running
Available Repositories | 1125
Downloaded Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | May 22, 2022, 21:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | us-east-1-3.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.6
-- | --
update_channel | stable
supervisor_version | supervisor-2022.05.1
docker_version | 20.10.9
disk_total | 31.3 GB
disk_used | 5.8 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.6.1), Studio Code Server (5.0.2), Terminal & SSH (9.4.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Sonoff</summary>

version | 3.0.5 (200f243)
-- | --
cloud_online | 1 / 1
local_online | 1 / 1

</details>

### Huawei Solar Setup

My Inverter is SIW300H M060 L1  without dongle

### Describe the issue

After the upgrade for version V200R001C00SPC121 of the inverter software I no longer can connect to either port 502 or 6607.

It was working normally before it. The upgrade was done automatically via either Huawei or the company that maintain the inverter. 

I just upgraded to version 1.0.1 of the integration. 

### Reproduction steps

1. add integration
2. try to connect to inverter and it fails
3.
...

### Relevant debug logs

```text
It's not generating any specific debug since it's not connecting
```

**Comment by jodewee** [comment]
Hi, when it is already configured with port 502, but after update i have to set it to 6607, is there a way to change it in the config? Or do i need to de.ete the integration and re-configure it again?

**Comment by wlcrs** [comment]
You need to delete and add it again
