### ISSUE TITLE
Add huawei logo's to hacs integration V2

### ISSUE THREAD

**Issue by Vato9394** [wlcrs/huawei_solar#6]
We still need to upload these files (logo & logo@2x) because the logo is only appearing inside the integration, not on the integration page.
![logo](https://user-images.githubusercontent.com/24278426/141649785-7d540515-2400-451a-bb18-11f0fa35b196.png)
![logo@2x](https://user-images.githubusercontent.com/24278426/141649786-c5580221-0556-424a-9496-11c0c3a6c0dc.png)
:

**Comment by wlcrs** [comment]
The documentation on home-assistant/brands mentions:

> If a domain is missing the logo.png file, the icon.png is served instead (if available).

So that's why I didn't duplicate it to the logo.png and logo@2x.png files.

Created a PR over there to add them nonetheless: https://github.com/home-assistant/brands/pull/2948
