### ISSUE TITLE
[Bug]: error while saving

### ISSUE THREAD

**Issue by Baltoros** [wlcrs/huawei_solar#62]
### System Health details

<html>
<body>

Wersja | core-2022.5.5
-- | --
Typ instalacji | Home Assistant OS
Wersja deweloperska | false
Supervisor | true
Docker | true
Użytkownik | root
Środowisko wirtualne | false
Wersja Pythona | 3.9.9
Rodzina systemu operacyjnego | Linux
Wersja systemu operacyjnego | 5.15.32-v7
Architektura procesora | armv7l
Strefa czasowa | Europe/Warsaw

</body>
</html>

### Huawei Solar Setup

does not exist

### Describe the issue

when writing the repository to the default directory
config / custom_components / huawei_solar

I am getting an error
- string index out of range

### Reproduction steps

1. error while saving
2.
3.
...

### Relevant debug logs

```text
does not exist
```

**Comment by wlcrs** [comment]
Duplicate of #63, which turned out to be transient.
