### ISSUE TITLE
String index out of range

### ISSUE THREAD

**Issue by MicheleMercuri** [wlcrs/huawei_solar#63]
Hi, when I will try to update the integration from 1.01 to 1.02 I get this error
![Screenshot_20220527_043511](https://user-images.githubusercontent.com/97225788/170619495-d5baaf5b-4e58-4321-b632-cd4d162d14ee.jpg)
How I can solve this issue?

**Comment by MicheleMercuri** [comment]
Fixed it's a bug of my HA installation. Sorry.

**Comment by wlcrs** [comment]
Hi, what was the bug in your HA? Other users also experience the same
issue? Can you help them?

**Comment by MicheleMercuri** [comment]
I think maybe a lastest hacs update installation problem. But I can't confirm it because I solved by restore a backup made a few days before lastest hacs update (1.25.1) and then update hacs to 1.25.1 again and then update all integration. 
Now all works fine.
First this fix I will try all with no success (unistalled Huawei solar, delete manually, install a previous version 1.0.1).
