### ISSUE TITLE
[Bug]: Connection with integration miss connection to inverter directly

### ISSUE THREAD

**Issue by SChellini** [wlcrs/huawei_solar#644]
### Describe the issue

When is using this integration , and home assistant it is connected , from the fusion solar app on mobile devices is not possible to connect directly to the invert on his SSID.The inverter SSID wifi network available , and can connect , but can not connect into the inverte , the app it said : already connect with some other device. I mean the connection is excusived  about home assistant if used this integration.

### Bescribe your Huawei Solar Setup

Inverter Type:
Inverter Firmware version:
SDongle present: yes / no
Power meter present: three phase / single phase / no
Battery: LG RESU xxkWh / LUNA2000 xxkWh / None
Battery Firmware version:

### How do you connect to the inverter?

Via the SDongle, wireless connection

### Upload your Diagnostics File

Drag & Drop your Diagnostics File here.

### Upload your relevant debug logs

```text
N/A
```

### Please confirm the following:

- [X] I'm running the latest release of Home Assistant.
- [X] I'm running the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [ ] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [ ] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by wlcrs** [comment]
This is a limitation of the inverter. Not something I can do anything about. If you want to use the FusionSolar app, you'll need to disable the integration and wait 1-2 minutes to connect.
