### ISSUE TITLE
[Bug]: v1.40A2 - State Class and Device Class Differs Between Batteries

### ISSUE THREAD

**Issue by Roving-Ronin** [wlcrs/huawei_solar#684]
### Describe the issue

Is this correct, as the existing 'battery' sensor that shows the total of all batteries has a state class of TOTAL, and device class of ENERGY. Whilst the new battery_1_x  type sensors for the same data, have the state class of MEASUREMENT and the device class of ENERGY_STORAGE (which is correct for a battery)

![image](https://github.com/wlcrs/huawei_solar/assets/108674933/745ca5c1-1cc1-4766-93a1-0e91290a6361)

Works either way, but flagging in case the existing sensor.battery_ sensors need to be updated to the newer state/device classes?

### Bescribe your Huawei Solar Setup

Inverter Type: SUN2000-5KTL-L1 (Qty 2)
Inverter Firmware version: V200R001C00SPC138
SDongle present: yes - V200R022C10SPC108
Power meter present: single phase
Battery:  LUNA2000 10kWh
Battery Firmware version: V100R002C00SPC125

### How do you connect to the inverter?

Via the SDongle, wireless connection

### Upload your Diagnostics File

N/A.

### Upload your relevant debug logs

```text
N/A.
```

### Please confirm the following:

- [X] I'm running the latest release of Home Assistant.
- [X] I'm running the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [X] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [X] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by wlcrs** [comment]
Thank you for noticing those two flaws. I've changed them all to "total" and "energy_storage".
