### ISSUE TITLE
[Feature Request]: Battery operating mode Time usage: set times in Home Assistant

### ISSUE THREAD

**Issue by assineu** [wlcrs/huawei_solar#695]
### Describe your feature request

You can also create/change the time periods in Home Assistant. Then you could connect the time control with Tibber, for example

### Proper usage

- [X] I confirm that this is not a bug report or support request
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by wlcrs** [comment]
https://github.com/wlcrs/huawei_solar/wiki/Time-of-Use-control
