### ISSUE TITLE
[Feature Request]: Power value for DC strings

### ISSUE THREAD

**Issue by elilei123** [wlcrs/huawei_solar#697]
### Describe your feature request

Hello Can you make the DC Power separately for String 1 and 2 i and a lot of People Need this 
We dont will use helper for this 
Is this working ? 

### Proper usage

- [X] I confirm that this is not a bug report or support request
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by wlcrs** [comment]
Those values are not exposed by the inverter, but can indeed be deduced from the voltage and current.

You will need to create a helper entity yourself to calculate them.

This integration does not do any computation on the values it receives itself, as to prevent a multiplication of measuring errors to cause havoc. I rather have users create helper entities themselves and be aware of the consequences than hide them inside the integration.
