### ISSUE TITLE
[Feature Request]: More verbose entity names

### ISSUE THREAD

**Issue by luzik** [wlcrs/huawei_solar#71]
### Describe your feature request

Now default entities do have names like:
sensor.active_power

I do not know if it tell me about whole house, sun2000, iron, lamp or another sun2000 in my grid
Please consider adding to default names some suffix or prefix like:

sensor.sun2000_active_power
sensor.solar_production_active_power
sensor.active_power_serialnumber

**Comment by wlcrs** [comment]
Entity names are derived from the displayed name to the end user. I will not change those. You are free to change them to something that suits your installation better manually of course.
