### ISSUE TITLE
[Bug]:  Grid-Connected, Grid connection with derating due to power rationing 

### ISSUE THREAD

**Issue by JohnMcLear** [wlcrs/huawei_solar#714]
### Describe the issue

When using FusionSolar & Dongle the Inverter works fine.  When using this integration I am unable to effectively use my PV/battery storage due to:

``Grid-Connected, Grid connection with derating due to power rationing ``

STR:
1. Remove Dongle.
2. Install and configure EW11
3. Install This integration, reboot HA.
4. In Devices > This integration > Connect via Network > ew11.lan port 8899 slaves 6,2,3
5. Look in Devices > This Integration > Ensure all inverters/batteries/smart meter are visible (They are).

Screen shots:
![all devices working](https://github.com/wlcrs/huawei_solar/assets/220864/6d19fc9b-3f3c-495f-b016-31b90b06c356)
![Working power meter](https://github.com/wlcrs/huawei_solar/assets/220864/2b828a71-fdd9-43d0-830e-098a4575747c)
![Working Inverters showing logs](https://github.com/wlcrs/huawei_solar/assets/220864/3bc5672a-00ff-4d33-aa37-2a78a62983f8)
![Error on Inverter showing Derating due to power rationining](https://github.com/wlcrs/huawei_solar/assets/220864/d7d1df47-7198-4e1b-b32a-530eaa09110f)
![Battery Time Of Use periods is 1](https://github.com/wlcrs/huawei_solar/assets/220864/1880ff19-a769-4a2b-82bf-94cef09a307a)

I'm not sure if the battery abnormal is related, the battery functions fine and has no errors/faults when using FusionSolar..

I'm also not sure if I need to recommission each inverter to ensure it wont attempt to speak to Fusion Solar Management system, I'd guess at yes but don't want to make any changes w/ out some additional eyeballs..

### Describe your Huawei Solar Setup

Inverter Type: 3x SUN2000-6KTL-L1 - See Daisy chaining documentation
Inverter Firmware version: V200R001C00SPC139
sDongle present: No, I'm using an EW11
Power meter present: single phase
Optimizers Present: No
Battery: 9x LUNA2000-SO 5kWh
Battery Firmware version: V100R002C00SPC127
Huawei Solar integration version: ???

### How do you connect to the inverter?

Over serial, with a serial-to-WiFi stick

### Upload your Diagnostics File

Drag & Drop your Diagnostics File here.
[config_entry-huawei_solar-cf67b76e647d9c7bbd8e02d643932326.json](https://github.com/wlcrs/huawei_solar/files/15387990/config_entry-huawei_solar-cf67b76e647d9c7bbd8e02d643932326.json)

### Upload your relevant debug logs

```text
No errors in logs when doing debug and running command...


cat home-assistant_huawei_solar_2024-05-21T09-47-56.135Z.log | grep huawei
```
```


### Please confirm the following:

- [X] I'm running the latest release of Home Assistant.
- [X] I'm running the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [X] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [X] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by JohnMcLear** [comment]
Update: I called the service ``huawei_solar.reset_maximum_feed_grid_power`` and it appears to have put the inverters back to normal on-grid mode.

I don't know why I needed to call that service: Ref: https://github.com/wlcrs/huawei_solar/wiki/Changing-Active-Power-Control

**Comment by Roving-Ronin** [comment]
@JohnMcLear I've seen this before on a users plant (2 x 5kW L1's) where the installer had set the 'Grid Code' on the inverters to the newest version of said codes for Australian users (i.e. Australia-AS4777_<A/B/C>_LV230). These new codes are less tolerant than the settings the prior codes (AS4777-<NSW/QLD etc>) applied, so normal operation for the inverters always runs with this message.  Battery operation was NOT affected by this message.

![image](https://github.com/wlcrs/huawei_solar/assets/108674933/209e8aa3-7d70-4b76-9d27-74310fe9d74b)

I note that your 'Device Status' for the inverter though has a message that IMHO I'd been looking more into (than the Inverter State) message.   i.e. "Grid Connection: Power Limited".

**Comment by JohnMcLear** [comment]
I have noticed that the batteries are NOT charging as they  should be..

Despite having enough power input.

![plenty of power input](https://github.com/wlcrs/huawei_solar/assets/220864/04e588a5-33b9-4005-9208-a2da52130803)

The batteries are not charging as expected.

![charging is weird](https://github.com/wlcrs/huawei_solar/assets/220864/3b0e711e-1b16-4c31-a2bf-dfaed4a7548b)

And instead the power is being fed to the grid.

![this should be ~0 when the batteries are not 100% full](https://github.com/wlcrs/huawei_solar/assets/220864/88fe80d2-8845-4f5f-945a-ed19e760b9b4)

**Comment by JohnMcLear** [comment]
I'm also seeing a lot of items in the Logbook that I wasn't experiencing in Fusion Solar..

![logbook](https://github.com/wlcrs/huawei_solar/assets/220864/a3e88cd4-2c46-4d14-b12f-b93060df35b0)

**Comment by JohnMcLear** [comment]
> @JohnMcLear I've seen this before on a users plant (2 x 5kW L1's) where the installer had set the 'Grid Code' on the inverters to the newest version of said codes for Australian users (i.e. Australia-AS4777_<A/B/C>_LV230). These new codes are less tolerant than the settings the prior codes (AS4777-<NSW/QLD etc>) applied, so normal operation for the inverters always runs with this message. Battery operation was NOT affected by this message.
> 
> ![image](https://private-user-images.githubusercontent.com/108674933/332395754-209e8aa3-7d70-4b76-9d27-74310fe9d74b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyOTQ5OTQsIm5iZiI6MTcxNjI5NDY5NCwicGF0aCI6Ii8xMDg2NzQ5MzMvMzMyMzk1NzU0LTIwOWU4YWEzLTdkNzAtNGI3Ni05ZDI3LTc0MzEwZmU5ZDc0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQxMjMxMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjEwNjNkYWU2NGZhYjdiYzIyN2M4ZDZkYzlmNzJjOGRlNzM4MGUzNDdkYjI1Zjg4Mjk5MDkzN2FkZjU0OGZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5KncVxkEidvRvvH9srt53H6fewg1StZIG98vgcIatpc)
> 
> I note that your 'Device Status' for the inverter though has a message that IMHO I'd been looking more into (than the Inverter State) message. i.e. "Grid Connection: Power Limited".

I'm using the same Grid Code that was set when I was using Fusion Solar.

**Comment by JohnMcLear** [comment]
At midnight the inverters decided to stop discharging the batteries to help w/ load on the grid.

At 8am the inverters decided to send most of my energy storage to the grid.

![image](https://github.com/wlcrs/huawei_solar/assets/220864/9c7a01b1-f059-4f80-bb24-09f740b97b45)

![image](https://github.com/wlcrs/huawei_solar/assets/220864/c1dc5ba3-cfe5-4725-99b4-3e5ad1253900)
![image](https://github.com/wlcrs/huawei_solar/assets/220864/98d6a84e-1761-4e1e-8f9d-3550763b2679)
![image](https://github.com/wlcrs/huawei_solar/assets/220864/5550e3b9-57d5-477e-9db3-ea004aae48dc)

Note the grid overvoltage error..

**Comment by JohnMcLear** [comment]
After updates still no progress.  For some reason I get a battery abnormal when using this plugin but not fusion solar.  I think my next step should be to do a full reset of all three inverters and setup from scratch..

I'm going to wait for wlcrs before I do that tho because I feel like other people could hit this issue when migrating.

**Comment by wlcrs** [comment]
Other reports of users with "locking" inverters were mostly due to the grid voltage getting too high (due to too many solar panel installations in the neighbourhood) and the inverter scaling back or even stopping production due to that. So maybe check your grid voltage readings to see if that is also the cause for your case?

Possibly the SDongle does something to balance your 3 inverters to mitigate the risk of having to scale back due to "overproduction" ?

I've always tried to make sure that using this integration has as little as unintended side-effects as possible. I do not change any settings without user interaction. So if you don't change any values in HA yourself, the integration will not change anything on the inverters/batteries.

**Comment by JohnMcLear** [comment]
For now I've switched back to FusionSolar.

I think this requires further time/effort and maybe @wlcrs needs equipment IE multiple inverters/batteries to replicate the issue?

**Comment by Roving-Ronin** [comment]
@JohnMcLear 
As Thijs mentioned, this is 100% to do with the grid settings that are applied by the settings within the inverter (and/or via FusionSolar).
I'd be checking g your grid settings first to confirm they have been correctly applied for the country / network your on.

**Comment by malakudi** [comment]
"Grid-Connected, Grid connection with derating due to power rationing" is not a problem,, it is an indication that inverter does not work at 100% because it either has limitations in grid export (zero export or other limits) or limits due to high voltage of the grid etc
2068: Battery Abnormal is a bug with firmware V200R001C00SPC138 and later when also using Dongle. I had the same issue I flashed again  V200R001C00SPC136 and problem resolved. I haven't yet tried V200R001C00SPC141 if problem is fixed but I doubt it, I have reported issue to Huawei but they haven't responded  yet, even though I told them issue is fixed when rolling back to older firmware.

**Comment by JohnMcLear** [comment]
Hey @malakudi thanks for your comment.

@malakudi I don't experience derating when using the dongle and FusionSolar

@malakudi 2068 was being experienced **without** the Dongle and I haven't seen it since I migrated back to FusionSolar.

@Roving-Ronin yeah I will re-try the integration and come back to you :)  Thanks for that suggestion.

**Comment by malakudi** [comment]
> Thanks all for your input
> 
> @malakudi I don't experience derating when using the dongle and FusionSolar
> 
> @malakudi 2068 was being experienced **without** the Dongle and I haven't seen it since I migrated back to FusionSolar.
> 
You do experience it, fusionsolar might not show it but if you check what is reported through modbus, it is what this integration shows.
Error 2068 does not show without dongle. Error is generated on inverter reboot. Have you rebooted your inverters recentrly? With 139 firmware + dongle, you will get the error with or without the integration.

**Comment by wlcrs** [comment]
I've added a link to this issue in the first section of https://github.com/wlcrs/huawei_solar/wiki/Connecting-to-the-inverter . I'm closing this issue as it is not a bug in the integration, but a limitation of the Huawei SUN2000 / LUNA2000 systems.

**Comment by spacemanspiff2007** [comment]
@JohnMcLear 
Can you try setting the inverter to a power limit (e.g. 70%) to the fusion solar app or portal and then back to unlimited?
It seems to show unlimited and only when setting to a limit and then back to unlimited the value is actually used.

**Comment by CristiXP** [comment]
<img width="976" height="290" alt="Image" src="https://github.com/user-attachments/assets/190e27b2-d333-48c8-af94-53e22275e5a5" />

Does anyone know, if I buy a modbus adapter and also keep the dongle, but use the connection to adapter for HA integration, will it work? Will I have the same issue reported here? I have 2x6KTL1 inv in cascade, 1 battery stack and 1 power meter and SDongle05, and currently with the second inverter in loop... I am unable to run the integration because of the timeouts and need a solution.

@wlcrs can the app be configured only to sniff modbus signals and not interogate the modbus? In order to have a rs485 reader on the network?

**Comment by tl5866** [comment]
If it helps:

- I have connected a Waveshare RS485 to POE (B) to the modbus.
- It only sniffs the modbus signal, as polling commands interfere with the SDongle.
- I could only sniff the Power Meter (DTSU666-H) data from the modbus, as it seems that the inverters and batteries data is not published on the bus (I would be happy to hear otherwise from anyone)

Here is the python script that I'm using to sniff the data:

```
import socket
import struct
import json
import time
import sys

# --- CONFIGURATION ---
IP_WAVESHARE = '192.168.0.165'
PORT = 502

def get_float(data, offset):
    """Extrait un Float32 Big Endian à l'offset donné"""
    try:
        chunk = data[offset : offset+4]
        return struct.unpack('>f', chunk)[0]
    except:
        return 0.0

def run_sniffer():
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.settimeout(10) # Timeout socket
    
    # Structure par défaut pour éviter le "Empty reply" dans HA
    result = {"status": "searching"}
    
    try:
        sock.connect((IP_WAVESHARE, PORT))
        buffer = b''
        start_time = time.time()

        while (time.time() - start_time) < 12: # Timeout global de 12s
            chunk = sock.recv(2048)
            if not chunk: break
            buffer += chunk

            # Pattern identifié : ID 11 (0x0b) + Func 3 (0x03) + Len 160 (0xa0)
            idx = buffer.find(b'\x0b\x03\xa0')
            
            if idx != -1:
                total_len = 165 # 3 Header + 160 Data + 2 CRC
                
                if len(buffer) >= idx + total_len:
                    payload = buffer[idx+3 : idx+163]
                    
                    # Mapping validé par tes scans Delta
                    result = {
                        "status": "ok",
                        "timestamp": int(time.time()),
                        # Courants et Tensions
                        "current_l1": round(get_float(payload, 0), 2),
                        "current_l2": round(get_float(payload, 4), 2),
                        "current_l3": round(get_float(payload, 8), 2),
                        "voltage_l1": round(get_float(payload, 12), 1),
                        "voltage_l2": round(get_float(payload, 16), 1),
                        "voltage_l3": round(get_float(payload, 20), 1),
                        # Puissances (48=Total, 52/56/60=Phases)
                        "power_total": round(get_float(payload, 48), 1),
                        "power_l1": round(get_float(payload, 52), 1),
                        "power_l2": round(get_float(payload, 56), 1),
                        "power_l3": round(get_float(payload, 60), 1),
                        # Énergies cumulées
                        "energy_import": round(get_float(payload, 112), 10),
                        "energy_export": round(get_float(payload, 144), 10)
                    }
                    break # On a notre trame, on sort.
            else:
                if len(buffer) > 4000: buffer = buffer[-2000:]
                
    except Exception as e:
        result["status"] = "error"
        result["error_msg"] = str(e)
    finally:
        sock.close()
        # On garantit une sortie JSON pour HA
        print(json.dumps(result))
        sys.stdout.flush()

if __name__ == '__main__':
    run_sniffer()
```

Here is the additional section in configaration.yaml:

```
command_line:
  - sensor:
      name: "Huawei Smart Meter Sniffer"
      unique_id: huawei_smart_meter_sniffer
      command: "python3 -u /config/scripts/huawei_sniffer.py"
      command_timeout: 20
      value_template: "{{ value_json.status | default('error') }}"
      json_attributes:
        - power_total
        - power_l1
        - power_l2
        - power_l3
        - voltage_l1
        - voltage_l2
        - voltage_l3
        - current_l1
        - current_l2
        - current_l3
        - frequency
        - energy_import
        - energy_export
      scan_interval: 5
```

EDIT:
it looks like connecting to Pins 1 and 3 (RS485-1) would allow the Waveshare to be the master. 
I'll try it out and post an update...
