### ISSUE TITLE
[Feature Request]: Entities with editable entries

### ISSUE THREAD

**Issue by spelzl** [wlcrs/huawei_solar#715]
### Describe your feature request

Please have a look at how the entities of the go-e charger HA integration look like with editable number fields and pull down sections. 
![go-e Charger HA Entities](https://github.com/wlcrs/huawei_solar/assets/82170464/3d349bd6-de54-4850-b81f-2ef976917812)

Could the Huawei HA integration have similar entities, e.g. for battery max discharger power?

### Proper usage

- [X] I confirm that this is not a bug report or support request
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by Roving-Ronin** [comment]
@spelzl 

You mean like this one that is documented...

![image](https://github.com/wlcrs/huawei_solar/assets/108674933/3bf12006-3eb0-4e5c-80a5-26a6c1655e7e)

**Comment by spelzl** [comment]
Hi @Roving-Ronin,
I run 1.3.3.
I can't find what you described:
![image](https://github.com/wlcrs/huawei_solar/assets/82170464/4d3c7b25-56cc-410f-aae5-2a1fc5b4f3b6)

**Comment by spelzl** [comment]
@Roving-Ronin do you have an idea when 1.4.0 will be officially released?
It appears as if 1.4.0a3 is close to become released soon.

**Comment by Roving-Ronin** [comment]
@spelzl only Thijs (WLCRS) knows release timeframes. V1.4.0a3 has been out for a while now, next is supposed to be v1.4.0a4

**Comment by wlcrs** [comment]
As stated in https://github.com/wlcrs/huawei_solar?tab=readme-ov-file#network-configuration:

Checking the Advanced: elevate permissions checkbox will:

- give you access to optimizer data
- **enable you to dynamically change your inverter and battery settings**
