### ISSUE TITLE
[Feature Please add some more sensors to your integration that would provide information on the energy production of each of the strings PV1, PV2, .... etc.Request]: 

### ISSUE THREAD

**Issue by SpainBoys** [wlcrs/huawei_solar#723]
### Describe your feature request

Please add some more sensors to your integration that would provide information on the energy production of each of the strings PV1, PV2, .... etc.
Thank you.
**sensor.inverter_input_power_pv_1**
{{ ((states.sensor.inverter_pv_1_voltage.state | float) * (states.sensor.inverter_pv_1_current.state | float)) | round(2) }}
**sensor.inverter_input_power_pv_2**
{{ ((states.sensor.inverter_pv_2_voltage.state | float) * (states.sensor.inverter_pv_2_current.state | float)) | round(2) }}

### Proper usage

- [X] I confirm that this is not a bug report or support request
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by wlcrs** [comment]
This value is not exposed by the inverter and is thus outside of the scope of this integration. You can define helpers to calculate those values yourself.
