### ISSUE TITLE
[Feature Request]: add "Charge To Grid" working mode

### ISSUE THREAD

**Issue by VederJay** [wlcrs/huawei_solar#73]
### Describe your feature request

There's already the option in this integration to set the working mode to either "Maximise Self Consumption" or "Time Of Use". The third working mode is "Charge To Grid". I can set this third option through the fusionsolar app (when logged in as installer), but not through this integration. 
I'm hoping this would be a minor change as the config entry already exists, maybe it's just an enum to be added or some such?

![image](https://user-images.githubusercontent.com/6883926/173082093-a3e53804-3f38-4d6c-a64d-c1e25372d36d.png)

**Comment by VederJay** [comment]
Works perfectly. Thanks for the speedy response and happy holidays. 
I'll leave the ticket open so there's a reminder for adding it to a release at some point :)

**Comment by wlcrs** [comment]
This was released in 1.1.1
