### ISSUE TITLE
[Feature Request]: Forcible Charge read register 47100 value to a sensor

### ISSUE THREAD

**Issue by feserdel** [wlcrs/huawei_solar#731]
### Describe your feature request

Currently Huawei allow read and control (write) Forcible Charge MODBUS register Address 47100.

![image](https://github.com/wlcrs/huawei_solar/assets/118628912/4e9bc4b1-1a24-41cd-b77f-b06b3c597728)

But the integration only allows write via services (huawei_solar.forcible_charge and huawei_solar.forcible_charge_soc).

I have an automation to start forcible charge under certain circumstances (eg when energy is cheap at night), but is impossible to know when ends. 

Also, is necessary to check if another forcible charge is ongoing before start new forcible charge cycle.

For this reason it will be good to read the state of forcible charge register to a sensor, and enable automation management.

### Proper usage

- [X] I confirm that this is not a bug report or support request
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by wlcrs** [comment]
Implemented in in v1.4.0. You can use the state attributes of the new sensor to retrieve different properties of the forcible (dis)charge function.

**Comment by feserdel** [comment]
Thank you!!
