### ISSUE TITLE
[Bug]: v1.4 - Issues and Observations

### ISSUE THREAD

**Issue by Roving-Ronin** [wlcrs/huawei_solar#741]
### Describe the issue

Hi Thijs,

Just updated a HA instance from 1.4.0a3 to v1.4 (and now 1.4.1.  Edit: Have now deleted upgraded plant and added it back in from scratch) and noticed:

1) After updating and restarting that the Huawei / WLCRS integration had disabled itself. Integration worked fine after realising what had happened and re-enabling it. Just mentioning this, in case others see the same situation occur. 
On the flipside, updated my own HA instance (and updated to 2024.6.3) and rebooted and didn't have this happen.

2) Looking at remote site with a battery and noticed there is a 'Sensor: Battery 1 Remaining charge/discharge time'.  Is this a new sensor, as I don't recollect seeing it before?

Also I note that even though the battery is currently charging from PV, this sensor is showing '0 min'.
Edit: 2+ days later and it still hasn't updated from '0 min'.

![image](https://github.com/wlcrs/huawei_solar/assets/108674933/cfb83af7-d0c4-4ba5-8fec-a93e4a5e0892)

![image](https://github.com/wlcrs/huawei_solar/assets/108674933/a2ac7c68-4f3a-4bcb-a2f3-6f2bfa040f2b)

3) A cosmetic issue, the mdi: / icon to the left of the batteries 'Remaining charge/discharge time' appears to be missing. Given all the other sensors have MDI defined, I'd assume this is meant to have one also?

4) In v1.4.1 the new Inverter 'Active Power Control' that reports the limit (or unlimited) that the inverter is set to. I note that this sensor is appearing in all inverters in a cascade. Given this sensor reads/writes its' data from the primary inverter (as it manages the overall setting for the combined value of all inverters managed by the primary inverter) is there a need for having this sensor made available upon all but the first / primary inverter? (Checked two sites with dual inverters, activated this sensor on the secondary inverter is it remains in unknown state fyi).  Assuming its possible to filter/block/remove it from all but the primary inverter in a cascade, is it worth deleting it for all inverters except the primary inverter?

Thanks for the great work and updates Thijs !

### Describe your Huawei Solar Setup

Inverter Type: 2 x L1 5kW inverters cascaded. Currently only primary inverter is operating (as it has a LUNA ESS attached)
Inverter Firmware version: V200R001C00SPC138
sDongle present: Yes
sDongle Type: sDongleA-05
sDongle Connectivitiy: WiFi
sDongle Firmware: V200R022C10SPC108
Power meter present: Single Phase
Optimizers Present: No
Battery: LUNA2000-SO 10kWh
Battery Firmware version: V100R002C00SPC125
Huawei Solar integration version: v1.4.1

### How do you connect to the inverter?

Via the SDongle, wireless connection

### Upload your Diagnostics File

Drag & Drop your Diagnostics File here.
[config_entry-huawei_solar-e7190a773e4143ed923016cd2d3a7e21.json](https://github.com/user-attachments/files/15882260/config_entry-huawei_solar-e7190a773e4143ed923016cd2d3a7e21.json)

### Upload your relevant debug logs

```text
Trying to drag and drop and fails.
```

### Please confirm the following:

- [X] I'm running the latest release of Home Assistant.
- [X] I'm running the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [X] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [X] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by amit-nz** [comment]
Just wanted to add that I have the same issue - 0 minutes remaining for charge/discharge time and mdi icon is missing also.

**Comment by Roving-Ronin** [comment]
It seems that heinemannj is also seeing this 'Remaining charge/discharge time' remains at '0 min' issue. See in this thread:  https://github.com/wlcrs/huawei_solar/issues/746#issuecomment-2189303477

**Comment by wlcrs** [comment]
2. Somebody suggested that this integration only makes sense in installations with a backup battery box?
3. Fixed with commit above
4. This is not documented by Huawei. Limiting it to the primary inverter would require me to write extra code. Is there any harm in having that entity available in the secondary inverters?

**Comment by Roving-Ronin** [comment]
Re 2. Just jumped onto a site I have access to with 2 x 5kW L1 and 1 x 15kW LUNA S0, including a Backup-Box (1p) and as usual it always APPEARS to be showing '0 min'. However, changing to show the last month of history its actually getting some data:

![image](https://github.com/user-attachments/assets/c1d20667-4db1-40b2-b5fe-0542b06afaf8)

What exactly is this sensor supposed to reflect / mean, as from the name you'd think it would be constantly updating to show how long to charge it or discharge during 'normal' operation.

Re 4. Not in the documentation, but that is how the inverters work, with the primary taking the overall limit and applying it across all the inverters in the cascase. On the above 2 x 5kW L1 cascade for example, it shows:

![image](https://github.com/user-attachments/assets/bc995574-d021-4c23-992c-59baa04f7332)

Whilst the secondary inverter for this sensor remains in 'unknown' state (as the primary inverter is controlling this for the whole cascade of inverters).

BTW this raises the question of is it worth looking to add an 'Inverters' (same as 'Batteries' was added in v.1.4.x), to contain sensors such as this? This might also reduce additional code to 'filter' it to only the primary inverter in a cascade, as instead it wouldn't be added to type=inverter, it would be for inverter(s), of which there would only be one as Huawei only supports up to 3 inverters in a cascade for a plant. I believe there would be a bit of coding required to do this, so maybe a 'longer term' goal to work towards?
