### ISSUE TITLE
[Feature Request]: Register: 37007 - batteries_rated_charge_power

### ISSUE THREAD

**Issue by heinemannj** [wlcrs/huawei_solar#745]
### Describe your feature request

`batteries_rated_charge_power`

Register: `37007`

**Really helpful for energy management optimazations**

Edit: Register already available in library

```
No.            : 6
Signal Name    : [Energy storage unit 1] Rated charge power
Read/Write     : RO
Type           : UINT32
Unit           : W
Gain           : 1
Address        : 37007
Quantity       : 2
Scope          : -
HUAWEILUNA2000 : √
LGRESU         : √

STORAGE_UNIT_1_RATED_CHARGE_POWER = "storage_unit_1_rated_charge_power"
rn.STORAGE_UNIT_1_RATED_CHARGE_POWER: U32Register("W", 1, 37007),
```

Potentially this one is the better one:

```
No.            : 16
Signal Name    : [Energy storage] Maximum charge power
Read/Write     : RO
Type           : UINT32
Unit           : W
Gain           : 1
Address        : 37046
Quantity       : 2
Scope          : The value is the smaller value of the sum of the maximum charge and discharge capability of the solar inverter and
                 the charge and discharge capability of the connected energy storage unit (ESU).
HUAWEILUNA2000 : √
LGRESU         : √

rn.STORAGE_MAXIMUM_CHARGE_POWER: U32Register("W", 1, 37046)
STORAGE_MAXIMUM_CHARGE_POWER = "storage_maximum_charge_power"
```

### Proper usage

- [X] I confirm that this is not a bug report or support request
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by Roving-Ronin** [comment]
@heinemannj 

An observation, the Huawei Modbus Registers Definitions (Issue 05 - 2023-02-16 is the last I've found) list this register, being for "[Energy storage unit 1] Rated charge power".

However there is no register defined for "[Energy storage unit **2**] Rated charge power"  (i.e. if a user has 2 [or more] batteries installed).

**Comment by heinemannj** [comment]
Must be a **wrong description in Huawei Modbus Registers documentation**:

![image](https://github.com/user-attachments/assets/e2a727bd-b5a4-4007-826e-218028162cd7)
![image](https://github.com/user-attachments/assets/9453a2f7-a8b7-47b1-af09-9a1e9f9a5aa4)

**`Max output power for a LUNA2000 can never be greater than 5kWh!`**

My setup contains:

|LUNA2000|Max output power|
|------------------------|---------|
|1 x LUNA2000-5-S0   | 2.5 kWh|
|1 x LUNA2000-10-S0 | 5.0 kWh|
|Total                           | 7.5 kWh|

**Comment by Roving-Ronin** [comment]
37007 should only report 5000W, maximum of it's a 10/15kWh LUNA. This being as that register is for Battery #1 (only).

37046 would be the better register to query as it's for 'Batteries', so would show the capacity for all attached batteries combined (ie 5000 + 2500 = 7500W, as your setup reports).

Just wondering as to use case for this, won't the Maximum Charge (number) under Batteries that v1.4 added do the same thing, or you want to see maximum possible versus the maximum that has been defined (in the number input)?

PS. iirc New LUNA S1 (7/14/21kWh) at its maximum goes up to 10kWh dis/charge.

**Comment by heinemannj** [comment]
**My final solution**: https://github.com/wlcrs/huawei_solar/issues/746

**Comment by wlcrs** [comment]
Done in #768
