### ISSUE TITLE
[Feature Request]: Register: 37009 - batteries_rated_discharge_power

### ISSUE THREAD

**Issue by heinemannj** [wlcrs/huawei_solar#746]
### Describe your feature request

`batteries_rated_discharge_power`

Register: `37009`

**Really helpful for energy management optimazations**

Edit: Register already available in library

```
No.            : 7
Signal Name    : [Energy storage unit 1] Rated discharge power
Read/Write     : RO
Type           : UINT32
Unit           : W
Gain           : 1
Address        : 37009
Quantity       : 2
Scope          : -
HUAWEILUNA2000 : √
LGRESU         : √

STORAGE_UNIT_1_RATED_DISCHARGE_POWER = "storage_unit_1_rated_discharge_power"
rn.STORAGE_UNIT_1_RATED_DISCHARGE_POWER: U32Register("W", 1, 37009)
```

Potentially this one is the better one:

```
No.            : 17
Signal Name    : [Energy storage] Maximum discharge power
Read/Write     : RO
Type           : UINT32
Unit           : W
Gain           : 1
Address        : 37048
Quantity       : 2
Scope          : The value is the smaller value of the sum of the maximum charge and discharge capability of the solar inverter and
                 the charge and discharge capability of the connected ESU.
HUAWEILUNA2000 : √
LGRESU         : √

rn.STORAGE_MAXIMUM_DISCHARGE_POWER: U32Register("W", 1, 37048)
STORAGE_MAXIMUM_DISCHARGE_POWER = "storage_maximum_discharge_power"
```

### Proper usage

- [X] I confirm that this is not a bug report or support request
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by Roving-Ronin** [comment]
@heinemannj 

An observation, the Huawei Modbus Registers Definitions (Issue 05 - 2023-02-16 is the last I've found) list this register, being for "[Energy storage unit 1] Rated discharge power".

However there is no register defined for "[Energy storage unit 2] Rated discharge power"  (i.e. if a user has 2 [or more] batteries installed).

**Comment by heinemannj** [comment]
I've installed a second Luna (5kWh) since a couple of days.

After adding the second one `batteries_rated_discharge_power` have been increased from 5000W to 7500W.
Clearly visible in FusionSolar portal.

**Comment by Roving-Ronin** [comment]
@heinemannj I assume as in Battery1 is a 10kWh or 15kWh providing 5000W maximum charge/discharge capacity, and Battery2 at 5kWh with 2500W maximum charge/discharge capacity, hence it showing as 7500W.

As I posted above, Huawei documentation has this listed as "[Energy storage unit 1] Rated discharge power", with this name formatting used to refer to physical battery 1. From what your seeing though, it would seem the Huawei documentation is incorrect and it should read as "[Energy storage] Rated discharge power" (as Huawei refers to other sensors that are for the 'overall' battery setup, or what WLCRS v1.4 recently added with the "Batteries" sensors).

**Comment by heinemannj** [comment]
**My actual inverter setup** as visible in FusionSolar portal:

![image](https://github.com/wlcrs/huawei_solar/assets/3251642/4db27026-3646-4388-a197-be7472395eac)
![image](https://github.com/wlcrs/huawei_solar/assets/3251642/c73d9cd1-1f40-4650-b5f3-0a90e7d7f5eb)

**My actual batteries setup** as visible in FusionSolar portal (in **summary: 10kWh + 5kWh**):
![image](https://github.com/wlcrs/huawei_solar/assets/3251642/51c8bdf2-0fcd-4495-837b-3344c6e8a1a6)

LUNA2000-1:
![image](https://github.com/wlcrs/huawei_solar/assets/3251642/258095b6-a8c0-40f8-bba2-1291e759c010)

LUNA2000-2:
![image](https://github.com/wlcrs/huawei_solar/assets/3251642/f7bc54a1-e231-4a07-86a3-fcc252db3045)

Device infos **by HA Huawei Solar Integration**:
![image](https://github.com/wlcrs/huawei_solar/assets/3251642/aaa0e192-acdc-4ab9-a476-c7b3006e5c36)

![image](https://github.com/wlcrs/huawei_solar/assets/3251642/cb89dff7-5cb8-4632-837a-72ad3f3cb3cd)

**Interesting notes**:

- `number.inverter_power_derating`
- `number.batteries_grid_charge_maximum_power`
- `number.batteries_maximum_discharging_power`

has all the **proper max values of 6600W**.

- ` number.batteries_maximum_charging_power`

has the **proper max value of 7500W**.

**Conclusion**:

In HA Huawei Solar Integration **somewhere in place but not distributed via sensors**:

- inverter_maximum_active_power: 6600
- batteries_rated_discharge_power: 6600
- batteries_rated_charge_power: 7500

In HA Huawei Solar Integration **not in place and not distributed via sensors**:

- inverter_rated_power: 6000
- batteries_rated_capacity: 15
- batteries_rated_charge_energy: 17.250

In addition some discrepancies in LUNA and LUNA 2 devices:

![image](https://github.com/wlcrs/huawei_solar/assets/3251642/d289f532-2172-498e-89f5-6ff46c4122bc)

![image](https://github.com/wlcrs/huawei_solar/assets/3251642/3d9738c2-4acf-4fa0-a5c4-cf595cc0b9c5)

I've found an **easy workarround** e.g.:

```
{%- macro globalVariables() %}
    {{- {
            'inverter_rated_power': 6000,
            'inverter_maximum_active_power': 6600,
            'batteries_rated_capacity': 15,
            'batteries_rated_charge_energy': 17.250,
            'batteries_rated_discharge_power': 6600,
            'batteries_rated_charge_power': 7500,
            'batteries_charge_end_time_expected': '14:00',
            'batteries_soc_setpoint_low': 15,
            'epexspot_quantile_setpoint_low': 0.15,
            'epexspot_quantile_setpoint_neutral': 0.33,
            'epexspot_quantile_setpoint_high': 0.8
        }|to_json -}}
{%- endmacro %}
```

```
{% from '032-emhass.jinja' import globalVariables %}
{% set var = globalVariables()|from_json %}
{% set bat_state = states('sensor.batteries_state_of_capacity')|float(0) / 100 %}
{{ (var.batteries_rated_capacity * bat_state) }}
```

**But this workarround is far away to maintain blueprints for millions of people to safe our earth ...**

**My vision**:

![image](https://github.com/wlcrs/huawei_solar/assets/3251642/ceca7d72-b899-41a3-8719-fdee9fc31fd4)

![image](https://github.com/wlcrs/huawei_solar/assets/3251642/b265dfa8-2c4f-403c-a43c-d8bb39c27667)

![image](https://github.com/wlcrs/huawei_solar/assets/3251642/52acad19-b2fb-40e9-962b-8da231ba7031)

**Comment by Roving-Ronin** [comment]
@heinemannj 
Sorry where's the 'easy workaround' actually installed and where is it scraping its data from?
Also, would you please be able to get back to me in regards working with others to standardise the derived sensors, entity names/ID's etc that we are all using? 
I'd love to be able to leverage your dashboards also, and also use Nick Jensens' "PEES" package for tracking its data, and SunSynk Card but at the moment each uses different entities / names / IDs etc  so its a nightmare to use more than one. Working to standardise upon a  'derived sensors standardised package' that all Huawei (& iStore in Australia) users could use going forward seems logical. ??

**Comment by heinemannj** [comment]
https://www.home-assistant.io/docs/configuration/templating/#reusing-templates

![image](https://github.com/wlcrs/huawei_solar/assets/3251642/59357dc3-ae1a-47a6-b5a9-4e459d87f536)

You only have to create the template file `032-emhass.jinja` in the folder `config/custom_templates` with the following content:

```
{%- macro globalVariables() %}
    {{- {
            'inverter_rated_power': 6000,
            'inverter_maximum_active_power': 6600,
            'batteries_rated_capacity': 15,
            'batteries_rated_charge_energy': 17.250,
            'batteries_rated_discharge_power': 6600,
            'batteries_rated_charge_power': 7500,
            'batteries_charge_end_time_expected': '14:00',
            'batteries_soc_setpoint_low': 15,
            'epexspot_quantile_setpoint_low': 0.15,
            'epexspot_quantile_setpoint_neutral': 0.33,
            'epexspot_quantile_setpoint_high': 0.8
        }|to_json -}}
{%- endmacro %}
```
Templates in this folder will be loaded at startup. To reload the templates without restarting Home Assistant, invoke the [homeassistant.reload_custom_templates](https://my.home-assistant.io/redirect/developer_call_service?service=homeassistant.reload_custom_templates) service.

**Comment by Roving-Ronin** [comment]
@heinemannj 

Hmm... OK. Yes that really isn't sustainable long term, as you commented, and not 'dynamic' for updating to what someone has as their setup (given it looks to be static defined values).
Looking at my /custom_templates directory and it only has a personal.jinja and power_control.jinja file. Looking at the name of the file you reference, it's actually another developers file also (EMHASS). There are some workarounds that I've been looking at for SunSynk and PEES (to automate setup), but really need Thijs to agreed to adding the additional sensors. Hopefully this would be entertained with the architecture changed in v1.4.x  (and set to disabled by default).

BTW could you please comment re the standardisation of sensors package work group...? Logic would dictate this as a common sense direction, through which most will benefit vs continuing with duplicating / maintaining 3-4 seperate sets of sensors. Thanks.

**Comment by heinemannj** [comment]
Standardisation of sensors package work groups is out of topic for this request!

My first view: Naming convention of PEES at this time is not fitting to my actual settings ...
My approach: To be much close to the nameing conventions provided by @wlcrs huawei_solar and all other integrations I needs to synchronize:

- huawei_solar
- epexspot
- tibber
- sun
- sun2
- solcast
- emhass
- myVaillant
- dwd_DeutscherWetterdienst
- Shelly
- ...

**Comment by heinemannj** [comment]
**My final solution and proposal:**

**Remove from Battery 1** as the `LUNA200 max output power is limited to 5kWh`:

![image](https://github.com/user-attachments/assets/87ee4ea0-f891-4fcc-82a5-32d700c3cf8f)

**Add to Batteries**:

![image](https://github.com/user-attachments/assets/e4dde4ce-aaaf-41e1-a6b0-201471aece24)

My setup contains below and is fitting exactly above figures:

|LUNA2000|Max output power|Capacity|
|------------------------|---------|--------|
|1 x LUNA2000-5-S0   | 2.5 kWh|5 kWh|
|1 x LUNA2000-10-S0 | 5.0 kWh|10 kWh|
|Total                           | 7.5 kWh|15 kWh|

Inverter: `SUN2000-6KTL-M1 (High Current)`

**Required code changes**:

```
    HuaweiSolarSensorEntityDescription(
        key=rn.STORAGE_RATED_CAPACITY,
        icon="mdi:home-battery",
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    HuaweiSolarSensorEntityDescription(
        key=rn.STORAGE_MAXIMUM_CHARGE_POWER,
        icon="mdi:home-battery-outline",
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=SensorDeviceClass.POWER,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    HuaweiSolarSensorEntityDescription(
        key=rn.STORAGE_MAXIMUM_DISCHARGE_POWER,
        icon="mdi:home-battery-outline",
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=SensorDeviceClass.POWER,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
```
```
            "storage_rated_capacity": {
                "name": "Rated Capacity"
            },
            "storage_maximum_charge_power": {
                "name": "Maximum charge power"
            },
            "storage_maximum_discharge_power": {
                "name": "Maximum discharge power"
            },
```

**Comment by Roving-Ronin** [comment]
@heinemannj 
I've created a branch in my fork, ready to request a PULL into WLCR integration at: https://github.com/Roving-Ronin/istore_solar/tree/Energy-Management-Optimisation-Sensors (including all the language files).

I'm not sure about the removing of the sensors from the individual batteries though. Could these still be of use to people? Would be good if Thijs would provide his views? (If possible, then will create a PULL based upon that feedback).

As an aside, whilst editing this and looking at entries such as:
- Active power Control (existing. If operated multiple inverters this represents the value for ALL inverters)
- Active Power (exists for each individual inverter, no 'Inverters' combined value)
- Daily Yield (exists for each individual inverter, no 'Inverters' combined value)
- Total Yield (exists for each individual inverter, no 'Inverters' combined value)

is that like how v1.4 introduced the 'Batteries' device, it would be really good if an 'Inverters' device could be added to the integration.

PS. In your code below (for use in en.json and strings.json) you have a typo. The P in P_max needs to be all lower case.
```
            "P_max": {
                "name": "Max active power"
            }
```

**Comment by heinemannj** [comment]
> @heinemannj I've created a branch in my fork, ready to request a PULL into WLCR integration at: https://github.com/Roving-Ronin/istore_solar/tree/Energy-Management-Optimisation-Sensors (including all the language files).
> 
> I'm not sure about the removing of the sensors from the individual batteries though. Could these still be of use to people? Would be good if Thijs would provide his views? (If possible, then will create a PULL based upon that feedback).

Remove the misleeding sensors and make the pull request:
- They have wrong values
- Inserted into the wrong device
- Fitting solution introduced

In any case Thijs needs to approve - If he has some doubt by reviewing, he will ask and discuss ...

**Comment by Roving-Ronin** [comment]
Ah OK, thanks for explaining, was getting a bit confused as the thread grew.

I will update the changes in the fork above, to remove those sensors and then submit a PULL. Will do tomorrow, as about to crash for the night.

PS. Do you have an idea on how an 'Inverters' (plural) could be added ?

**Comment by heinemannj** [comment]
> PS. Do you have an idea on how an 'Inverters' (plural) could be added ?

No - in addition this will be the biggests change since the last couple of years - to be initiated by the owner

**Comment by wlcrs** [comment]
Done in #768
