### ISSUE TITLE
[Feature Request]: Register: 30073 - inverter_rated_power

### ISSUE THREAD

**Issue by heinemannj** [wlcrs/huawei_solar#748]
### Describe your feature request

`inverter_rated_power`

Register: `30073`

**Really helpful for energy management optimazations**

Edit: Already available in library

```
RATED_POWER = "rated_power"
rn.RATED_POWER: U32Register("W", 1, 30073)
```
### Proper usage

- [X] I confirm that this is not a bug report or support request
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by Roving-Ronin** [comment]
@heinemannj 

This request is the same as I currently have raised in discussion with Thijs. See: https://github.com/wlcrs/huawei_solar/discussions/677#discussioncomment-9827841

This link includes what appears to be the registers that support querying this data. Alas my coding skills don't reach into the python world and I can't work out how to add them and submit a pull to the Huawei-Library. Hopefully Thijs would agree to add them with v1.4, even if disabled by default?

BTW what are you trying to do, as there's other efforts going on to provide some of these type of sensors outside of WLCR integration (using data from it). Such as:

![image](https://github.com/wlcrs/huawei_solar/assets/108674933/c1fbe8c5-0b22-4c74-8d9c-757c34a2a7ed)

Note: The Batteries rated capacity is the one above I'm trying to get going. There are registers for each battery module that can be queried, but that would be a nightmare from the Huawei-Library side (meaning 3 register per battery to call, and 2 batteries per inverter ...and potentially 4 per with the new LUNA2000 S1 7/14/21kWh model).

I've tried to tag you previously (hard given Github removed messaging) to ask if you would be interested in collaborating on standardising the derived sensors for Huawei (& iStore, as they are OEM'ed in Australia) + WLCRS. Currently you've got a good range of sensors for various things, https://github.com/JensenNick has a good package (or two) also tracking power flows, costs / savings / ROI etc.  

![image](https://github.com/wlcrs/huawei_solar/assets/108674933/d7f14383-4c5b-4f5e-9986-48c0186597c6)

With differing versions of sensors, with different ID's / names etc we however end up with confusion/issues when using another package/card that expects its own sensor entities.  Such as:

![SunSynk_WLCRS_v1 4](https://github.com/wlcrs/huawei_solar/assets/108674933/a2b0448e-1242-4aca-81f0-54e5e326fd54)

Thinking that logical idea would be to combine and every agree on a standard set of derived sensors that 'any and all' addons and cards etc could leverage. ???

**Comment by heinemannj** [comment]
**My final solution**: https://github.com/wlcrs/huawei_solar/issues/746

**Comment by wlcrs** [comment]
Done in #768
