### ISSUE TITLE
[Feature Request]: Register: 37758 - batteries_rated_capacity

### ISSUE THREAD

**Issue by heinemannj** [wlcrs/huawei_solar#749]
### Describe your feature request

Unfortunately I've not found in Huawei Solar Inverter Modbus Interface Definitions ...
but really helpful for energy management optimazations.

Seen in FusionSolar portal:

![image](https://github.com/wlcrs/huawei_solar/assets/3251642/fadb7e3b-2ca7-44ba-ab9a-10e67e9881b4)

Edit:
**Register for 'batteries_rated_capacity': `37758`** already available in libray

```
rn.STORAGE_RATED_CAPACITY: U32Register("Wh", 1, 37758),
STORAGE_RATED_CAPACITY = "storage_rated_capacity"
```

### Proper usage

- [X] I confirm that this is not a bug report or support request
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by Roving-Ronin** [comment]
@heinemannj 

This request is the same as I currently have raised in discussion with Thijs. See: https://github.com/wlcrs/huawei_solar/discussions/677#discussioncomment-9827841

This link includes what appears to be the registers that support querying this data. Alas my coding skills don't reach into the python world and I can't work out how to add them and submit a pull to the Huawei-Library. Hopefully Thijs would agree to add them with v1.4, even if disabled by default?

BTW what are you trying to do, as there's other efforts going on to provide some of these type of sensors outside of WLCR integration (using data from it). Such as:

![image](https://github.com/wlcrs/huawei_solar/assets/108674933/c1fbe8c5-0b22-4c74-8d9c-757c34a2a7ed)

Note: The Batteries rated capacity is the one above I'm trying to get going. There are registers for each battery module that can be queried, but that would be a nightmare from the Huawei-Library side (meaning 3 register per battery to call, and 2 batteries per inverter ...and potentially 4 per with the new LUNA2000 S1 7/14/21kWh model).

I've tried to tag you previously (hard given Github removed messaging) to ask if you would be interested in collaborating on standardising the derived sensors for Huawei (& iStore, as they are OEM'ed in Australia) + WLCRS. Currently you've got a good range of sensors for various things, https://github.com/JensenNick has a good package (or two) also tracking power flows, costs / savings / ROI etc.  

![image](https://github.com/wlcrs/huawei_solar/assets/108674933/d7f14383-4c5b-4f5e-9986-48c0186597c6)

With differing versions of sensors, with different ID's / names etc we however end up with confusion/issues when using another package/card that expects its own sensor entities.  Such as:

![SunSynk_WLCRS_v1 4](https://github.com/wlcrs/huawei_solar/assets/108674933/a2b0448e-1242-4aca-81f0-54e5e326fd54)

Thinking that logical idea would be to combine and every agree on a standard set of derived sensors that 'any and all' addons and cards etc could leverage. ???

**Comment by Roving-Ronin** [comment]
@heinemannj 

This register is already in the huawel library:  rn.STORAGE_RATED_CAPACITY: U32Register("Wh", 1, 37758),

Prior to seeing if Thijs would allow adding this sensor into the integration, by lodging a PULL request, would you like to try these changes and see if they work for you also ? 

In sensor.py add the STORAGE_RATED_CAPACITY section, so it sits between STORAGE_STATE_OF_CAPACITY abd STORAGE_RUNNING_STATUS. Like this:

```
BATTERIES_SENSOR_DESCRIPTIONS: tuple[HuaweiSolarSensorEntityDescription, ...] = (
    HuaweiSolarSensorEntityDescription(
        key=rn.STORAGE_STATE_OF_CAPACITY,
        icon="mdi:home-battery",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    HuaweiSolarSensorEntityDescription(
        key=rn.STORAGE_RATED_CAPACITY,
        icon="mdi:battery-charging",
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    HuaweiSolarSensorEntityDescription(
        key=rn.STORAGE_RUNNING_STATUS,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
```

Then in strings.json, same as above add the RATED_CAPACITY section, so it looks like:

```
            "storage_state_of_capacity": {
                "name": "State of capacity"
            },
            "storage_rated_capacity": {
                "name": "Rated Capacity"
            },
            "storage_running_status": {
                "name": "Status"
            },
```

Restart HA and then see if in the Batteries device, in its Diagnostic section you have:

![image](https://github.com/user-attachments/assets/068ed98c-2c6e-4c75-8832-e6537a4e9cee)

Then open the sensor and make sure the name is displaying as 'Batteries Rated Capacity' and (click the settings/cog wheel) that the Entity ID = sensor.batteries_rated_capacity.

**Comment by heinemannj** [comment]
You have to change the unit from `Watt` to `KILO_WATT_HOUR`:

```
    HuaweiSolarSensorEntityDescription(
        key=rn.STORAGE_RATED_CAPACITY,
        icon="mdi:home-battery",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
```

In addition I had to modify the `en.json` as well.

My entity_ID was `sensor.batteries_none` - potentially due to the issue that I had not modified `en.json` at my first try.

**Comment by Roving-Ronin** [comment]
@heinemannj The Huawei documentation refers to the output in Wh, but I found it displated as '15,000'  (for a 15kWh LUNA) when I first tried it, hence I listed the Unit of Measurement as 'Watt'. What do you get when you use 'KILO_WATT_HOUR' ? I would have thought that would see you get '15,000kWh' ?

Ahh thanks re the en.json I totally overlooked that and was wondering where that was set.

**Comment by heinemannj** [comment]
![image](https://github.com/user-attachments/assets/0ef28562-3e09-42d7-a2d3-9d0f1ac28d73)

**Comment by heinemannj** [comment]
Changing from `KILO_WATT_HOUR` to `WATT_HOUR` finally results to:

![image](https://github.com/user-attachments/assets/5672226e-b01b-4bd3-9a37-be2e3b36e188)

![image](https://github.com/user-attachments/assets/afacfd39-873a-43c9-9595-15e0bc32f0f2)

```
    HuaweiSolarSensorEntityDescription(
        key=rn.STORAGE_RATED_CAPACITY,
        icon="mdi:home-battery",
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
```

**Comment by heinemannj** [comment]
**My final solution**: https://github.com/wlcrs/huawei_solar/issues/746

**Comment by wlcrs** [comment]
Done in #768
