### ISSUE TITLE
[Feature Request]:  convert the inverters.active.power sensor to energy instead of power. State to total instead of measurement

### ISSUE THREAD

**Issue by gverbist** [wlcrs/huawei_solar#752]
### Describe your feature request

To be able to add the sensors to the energy dashboard the inverter sensors need to be of device_class: energy. Currently this is power.

For the state_class this should be come total_increasing instead of measurement.

Having the wrong device class/state_class prevents using the energy dashboard in home assistant.

### Proper usage

- [X] I confirm that this is not a bug report or support request
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by Roving-Ronin** [comment]
The integration provides access to the Huawei registers only. As it stands this means there are Active Power sensors that show the 'that instant' use of power, whilst there is also Energy meters that show Energy in kWh that track:
- Grid Import / Export
- Inverter(s) Total PV today / lifetime
- Batteries total charge / discharge for today and lifetime.

If you want an energy meter that tracks how much you've used in your house for today and another for how much you've imported or exported from the grid, then you need to create it.
Refer to the Wiki that has examples of this. Alternatively look at the Sunsynk Powerflow card for HA, off the documentation there is a link for Huawei with WLCRS, you can either use that as an example for how to write it or wait till I get a moment to update that yaml (that you can then copy and paste) to be up to date with WLCRS v1.4.

Also lookup energy_meter integration or the HA standard version utility_meter.
