### ISSUE TITLE
[Bug]: 'Efficiency' reports wrong percentage

### ISSUE THREAD

**Issue by jov58** [wlcrs/huawei_solar#77]
### System Health details

-

### Huawei Solar Setup

I use this nice integration for my SUN2000-12KTL-M2 inverter with a SmartDongle and UTP cable.

### Describe the issue

The field `Efficiency` reports the value `655.35%` (FFFF?) when the inverter is stand-by and obviously doesn't represent the real value. I suggest to replace this value by `0.0%` (or `unvailable`?) so graphs and other data views are neater.

### Reproduction steps

1. Install the integration.
2. Look at the sensor `Efficiency `when the inverter is stand-by.

### Relevant debug logs

```text
-
```

**Comment by wlcrs** [comment]
Can you please let me know which version of the integration you are using?

**Comment by wlcrs** [comment]
Closed due to inactivity

**Comment by luzik** [comment]
I am using the newest one, and issue is still there

**Comment by wlcrs** [comment]
Revisited the code in question, and found a lingering bug: https://gitlab.com/Emilv2/huawei-solar/-/commit/e9a3dcd521bd93d1ba762a0534ea2e706fdfd19b
