### ISSUE TITLE
[Feature Request]: Expose "System Time" and "Time Zone" registers

### ISSUE THREAD

**Issue by Cis4Cookies** [wlcrs/huawei_solar#771]
### Describe your feature request

My setup involves an offline SUN2000-6KTL-M1 inverter, that is deliberately commissioned without a smart dongle since I do not want to expose all my energy data to Huawei nor use the FusionSolar app for energy visualization.

I have a direct serial connection to my RPi4 which is running HA OS. The integration works like a charm so far.

The only drawback of an offline inverter is, that over time the inverter's system time goes out of synch, causing delays in time-based Modbus registers like "daily yield", etc. Currently, I connect to the inverter WiFi every now and then to adjust the time manually.

Would it be possible to add the corresponding registers shown below, so that we could use a simple HA automation for setting the system time and time zone regularly, e.g. on a daily basis.

![TimeZone](https://github.com/user-attachments/assets/ac1f83b3-7b70-42b6-b08d-da0b554b8860)
![SystemTime](https://github.com/user-attachments/assets/1e60ad96-ef3f-4a2d-8582-c8907397c7dc)

### Proper usage

- [X] I confirm that this is not a bug report or support request
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by Roving-Ronin** [comment]
@Cis4Cookies have you tried just installing the sDongle and connecting it to the LAN/Internet, so it can then do SNTP time updates, but then simply blocking access on your home firewall to intl.fusionsolar.huawei.com or *.fusionsolar.huawei.com (or its specific IP addresses)?

**Comment by wlcrs** [comment]
While I appreciate your situation, adding this entity to the integration would surely confuse people: configuration entities are only updated every 5 minutes, making sure that it would always show a wrong number in HA.

Feel free to add it yourself by following the steps described in https://github.com/wlcrs/huawei_solar/wiki/Defining-custom-sensors, but applied to https://github.com/wlcrs/huawei_solar/blob/main/number.py#L64 instead.
