### ISSUE TITLE
[Feature Request]: Add support for Active Power Control Mode selection

### ISSUE THREAD

**Issue by jenssvedlund** [wlcrs/huawei_solar#779]
### Describe your feature request

From the fusion solar app and web interface it's possible to select whether to limit the export of excess power generated.
However, this is not possible to change with the integration.

![image](https://github.com/user-attachments/assets/29f70665-2136-474b-95b9-ea7075dc6804)

Would it be possible to add support for changing the Active Power Control Mode?

### Proper usage

- [X] I confirm that this is not a bug report or support request
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by vdvmichel** [comment]
You can do that with service…
