### ISSUE TITLE
[Bug]: The integration fails to install

### ISSUE THREAD

**Issue by lomtaslipptas** [wlcrs/huawei_solar#784]
### Describe the issue

I had an installation of Huawei Solar in the past. It was deleted, because I found other solutions to get the informations and there were issues with having multiple modbus connections. After now switching to tibber I need the posibility to load the battery when there is not much solar energy and the energy price is low. This would be possible with that integration.
While trying to install it now again it always says that the device is configured already.
![image](https://github.com/user-attachments/assets/42b54a4f-9a0e-402b-a89e-9e355026b114)
Looking in my integrations there is no huawei solare integration set up. Looking into the entity list I can find entities from an huawei solar integration but there have all the information that there are deactivated.
![image](https://github.com/user-attachments/assets/34bc0512-0858-4344-a6a3-74ce290e09bd)
For me it seems like the old installation of the integration is not deleted completely. That leads now to the point that I cannot install it.
What can I do?

### Describe your Huawei Solar Setup

not necessary for that bug.

### How do you connect to the inverter?

Via the SDongle, wireless connection

### Upload your Diagnostics File

I cannot post the diagnostic files because I cannot install the integartion.

### Upload your relevant debug logs

```text
No relevant debug logs.
```

### Please confirm the following:

- [X] I'm running the latest release of Home Assistant.
- [X] I'm running the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [X] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [X] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by Electronlibre2012** [comment]
Hello,

i have uninstall the integrationand now i cant install it again : "unexpected error" after credential validation. I test everything : i can ping 192.168.200.1 from my lan, static route are operationnal, openwrt gateway works and is connected to my LAN by 192.168.1.2 and connect to the wlan of my SUN-2000 to 192.168.200.1...

![Sans titre](https://github.com/user-attachments/assets/99a66fcd-f043-485e-b531-f615adab0194)

is there something to do please? my backup is too old for HA...

Thanks
