### ISSUE TITLE
[Feature Request]: Operating status/ON-OFF switch

### ISSUE THREAD

**Issue by geraldFS** [wlcrs/huawei_solar#79]
### Describe your feature request

Hello!

Is it possible to get the status from the inverter?

- Standby
- Operation
- out

and possibly restart the inverter?

Wouldn't be so wrong sometimes, at the weekend there was a case that the inverter switched itself off due to a thunderstorm.
Undervoltage in one phase was detected.

The restart was only possible via a switch on the device or via the web interface on the Huawei.

Thanks!

**Comment by wlcrs** [comment]
The inverter exposes a lot of state, which cannot be easily exposed in home assistant into one entity, as multiple states can be active at once:

![image](https://user-images.githubusercontent.com/2150060/175894260-30a7ac7c-4e28-4f51-91da-3ffee4abed6d.png)
![image](https://user-images.githubusercontent.com/2150060/175894315-22afd2cb-fb7b-4806-a692-99c6776ab1d2.png)

Note that there is no 'out' status, but it does have a lot of alarm bit-codes. I could expose the active alarms as a comma-separated list of text. This would allow you to check for values via jinja-filters in HA.

I'm not aware of a restart-functionality via Modbus. You'll need to do this manually/via FusionSolar web

**Comment by tomderidder** [comment]
@wlcrs Is it feasable to build in some code to expose alarms etc.? We have quite some alarms from the inverter lately due to high voltage, and it would be great  to have this information in ha as well...

(And thanks a lot for the great job you did!)

**Comment by numanx11** [comment]
@wlcrs It would be great to add just the Shutdown feature or reset.
Sometimes it happens that the inverter connectivity to Huawei NMS fails and a reboot/reset for the inverter helps.

Meanwhile the inverter is accessible from the local network.

**Comment by wlcrs** [comment]
The extra state and alarm entities have been added in [v1.1.4](https://github.com/wlcrs/huawei_solar/releases/tag/1.1.4). 

As there is no documented way to perform a restart of the inverter via Modbus, I cannot add this feature.
