### ISSUE TITLE
[Bug]: Optimizer shown as unavailable at night

### ISSUE THREAD

**Issue by berta24** [wlcrs/huawei_solar#795]
### Describe the issue

Optimizer are shown as unavailable by night and that is correct, but value should remain numerical
in my case i have production per optimizer and it gives errors at night
![image](https://github.com/user-attachments/assets/6ed0339b-8e10-4bc4-8756-cec7dea5847c)

because it says unknown on every value instead of 0
![image](https://github.com/user-attachments/assets/7000697a-0732-419a-bc37-4ecf8a14cd51)

### Describe your Huawei Solar Setup

Inverter Type:  SUN2000-6KTL-M1
Inverter Firmware version:  V100R001C00SPC165
sDongle present: Yes 
sDongle Type: sDongleA-05 Ethernet)
sDongle Connectivitiy:Ethernet 
sDongle Firmware:  latest
Power meter present: three phase 
Optimizers Present: Yes 
Battery: None
Huawei Solar integration version: 1.4.1

### How do you connect to the inverter?

Via the SDongle, wired connection

### Upload your Diagnostics File

[config_entry-huawei_solar-10f2ba3754c09122570d17ff8163f709.json](https://github.com/user-attachments/files/16642258/config_entry-huawei_solar-10f2ba3754c09122570d17ff8163f709.json)

### Upload your relevant debug logs

```text
no problems that requires logs
```

### Please confirm the following:

- [X] I'm running the latest release of Home Assistant.
- [X] I'm running the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [X] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [ ] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by wlcrs** [comment]
This was tried in the past but proved to cause more issues than solutions. It is not possible to have correct numbers for all sensors when unavailable. (Example: temperature)

Use availability test in your template sensor to correctly work around this
