### ISSUE TITLE
[Feature Request]: Readme modification

### ISSUE THREAD

**Issue by Zephael86** [wlcrs/huawei_solar#80]
### Describe your feature request

Can you please add in the guide that the installer's password can be 00000000a (8 zeros).
It was said by the guy who installed my system 3 weeks ago that newer devices have this default password.
My SUN2000-6KTL-M1GIN300-6KTL-M1 works in this way already.

**Comment by wlcrs** [comment]
Feel free to create a pull request to address this issue. I did not include it in the README at the time I wrote it to prevent users to start using this integration without fully understanding that it enables them to edit 'sensitive' values.
