### ISSUE TITLE
[Bug]: values goes to 0 and back and Go back to 0

### ISSUE THREAD

**Issue by elilei123** [wlcrs/huawei_solar#805]
### Describe the issue

Hello,
My inverter gives me the Value 5000w Then 0 Then 4900W …… what is wrong 
This is After Update 
The Same by Meter data 

### Describe your Huawei Solar Setup

Inverter Type: Sun 8 KTL
Inverter Firmware version: NEWEST 
sDongle present: Yes 
sDongle Type: sDongleA-05 (WiFi 
sDongle Connectivitiy: WiFi 
sDongle Firmware:  NEWEST WITH LIVE DATA 
Power meter present: three phase 
Optimizers Present: No
Battery: LUNA2000-SO 10kWh 
Battery Firmware version: newest
Huawei Solar integration version: 

### How do you connect to the inverter?

Via the SDongle, wireless connection

### Upload your Diagnostics File

Drag & Drop your Diagnostics File here.
![IMG_4772](https://github.com/user-attachments/assets/b7d7a924-5757-4a7a-ba7c-421eec1c70a0)
![IMG_4771](https://github.com/user-attachments/assets/69c7cbc8-7c30-4a83-b892-ef9be16a49cb)

### Upload your relevant debug logs

```text
Nothing is Loading
```

### Please confirm the following:

- [X] I'm running the latest release of Home Assistant.
- [X] I'm running the latest release of this integration.
- [ ] I did not find an existing issue describing this problem.
- [ ] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [ ] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by wlcrs** [comment]
Lowering the time between updates is at your own risk. I don't provide support for that.

**Comment by elilei123** [comment]
ah okay but what can i do
________________________________
Von: Thijs W. ***@***.***>
Gesendet: Sonntag, 15. September 2024 18:20
An: wlcrs/huawei_solar ***@***.***>
Cc: elilei123 ***@***.***>; Author ***@***.***>
Betreff: Re: [wlcrs/huawei_solar] [Bug]: values goes to 0 and back and Go back to 0 (Issue #805)


Lowering the time between updates is at your own risk. I don't provide support for that.
