### ISSUE TITLE
[Feature Request]: Deprecated constant - POWER_VOLT_AMPERE_REACTIVE

### ISSUE THREAD

**Issue by homerojleal** [wlcrs/huawei_solar#811]
### Describe your feature request

Slight update to integration constants/variables warning currently in HA logs:

Logger: homeassistant.const
Source: helpers/deprecation.py:197
First occurred: 11:46:18 (1 occurrences)
Last logged: 11:46:18

POWER_VOLT_AMPERE_REACTIVE was used from huawei_solar, this is a deprecated constant which will be removed in HA Core 2025.9. Use UnitOfReactivePower.VOLT_AMPERE_REACTIVE instead, please report it to the author of the 'huawei_solar' custom integration

### Proper usage

- [X] I confirm that this is not a bug report or support request
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by robimarko** [comment]
I think its already fixed via:
https://github.com/wlcrs/huawei_solar/commit/19f012a6460e89efe28e74d306cd5cd846f82359
