### ISSUE TITLE
[Feature Request]: Missing Option Field: "Charge/Discharge"

### ISSUE THREAD

**Issue by christianarth** [wlcrs/huawei_solar#813]
### Describe your feature request

On the FusionSolar website, there is an option in the battery configuration under Forced charge/discharge to change ‘Charge/Discharge’ from ‘Stop’ to ‘Charge’ or ‘Discharge’. This field is missing in Home Assistant. This toggle would be very useful to be able to charge the battery automatically depending on the electricity price in combination with ‘Charge from AC’.
Or am I overlooking this feature?

### Proper usage

- [X] I confirm that this is not a bug report or support request
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by vdvmichel** [comment]
You can do that with service…

**Comment by wlcrs** [comment]
What 👆 said
