### ISSUE TITLE
[Bug]: sensor voltage to ground

### ISSUE THREAD

**Issue by kekomovil2** [wlcrs/huawei_solar#814]
### Describe the issue

"Hello, I have noticed that the sensor shows very high values of 719.7V in the 600W-P optimizer model, while in the 450W-P2 model it shows normal values of 3.0V."

Español:
Buenas, me he dado cuenta que el sensor marca valores muy altos 719,7V en el modelo optimizador 600W-P, en cambio en el modelo 450W-P2 si marca valores normales 3.0V

### Describe your Huawei Solar Setup

Inverter Type: SUN2000-6KTL-L1
Inverter Firmware version: V200R001C00SPC136
Power meter present: single phase
Optimizers Present: Yes 600W-P, 450W-P2
Huawei Solar integration version: 1.3.1

### How do you connect to the inverter?

Over serial, with a serial-to-USB stick

### Upload your Diagnostics File

Drag & Drop your Diagnostics File here.
[config_entry-huawei_solar-bb0e1d79aebdf25c2fd2d0ec3a095eea-4.json](https://github.com/user-attachments/files/17174235/config_entry-huawei_solar-bb0e1d79aebdf25c2fd2d0ec3a095eea-4.json)

### Upload your relevant debug logs

```text
No consigo verlo
```

### Please confirm the following:

- [X] I'm running the latest release of Home Assistant.
- [X] I'm running the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [X] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [ ] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by wlcrs** [comment]
No debug log = nothing for me to work with
