### ISSUE TITLE
[Feature Request]: Off-grid controls

### ISSUE THREAD

**Issue by bsergei** [wlcrs/huawei_solar#819]
### Describe your feature request

Is it possible to add following features to controll off-grid mode?

1. Off-grid mode: enable/disable
2. Grid-tied/Off-grid mode switching: automatic/manual
3. In manual switching mode there is additional command exists in FusionSolar to activate off-grid mode.

https://support.huawei.com/enterprise/en/doc/EDOC1100167258/e85f8ed5/setting-the-grid-tied-and-off-grid-ess-mode

### Proper usage

- [X] I confirm that this is not a bug report or support request
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by wavelov3r** [comment]
+1, it can help when there is a mains overvoltage (it stops the inverter, and the battery does not discharge)
