### ISSUE TITLE
Connecting to the inverter -wiki: Sample case  Using a dedicated WLAN Bridge: TP-link TL-WR802N

### ISSUE THREAD

**Issue by MEKadan** [wlcrs/huawei_solar#82]
From wiki mentioned above:

How exactly you configure the router?
- Setting the client mode is OK
- I get an IP for TP-Link in my 192.168.1.x network after setting it into client mode.
- In TP-Link I can feed in the parameters for the inverter ap ( host to be connected in client mode, that is SSID & PW)

Now, I have not set the DHCP in TP-Link, i'm in undertstanding it is not used in client mode.
I have installed the FusionSolar app, as long as it is needed, to get the initial connection and I can get to commissioning etc. However, I have not set the router connections, because the whole point of using this dedicated wlan bridge is to isolate my home network from these chinese systems.

Also the static route has been set in mys asus router so tha network/host is 192.168.200.0, netmask 255.255.255.0 and gateway is the address of TP-Link 

I can access TP-Link OK, but cannot see anything behind it (well, there should be only inverter at 192.168.200.2), I cannot ping it or traceroute it.

Should it be answering at this stage or are there still things to be done?

inverter model is SUN2000MA-4KTL-M1 firmware is  V100R001C00SPC141

The other thing I have not figured out yet: The is also the Sdongle installed, but I have not seen it transmitting anuy SSID's or anything How do I / Should I connect to it? 

(BTW, is this a correct place for this kind of issues, or is there some other forum for these?)

**Comment by wlcrs** [comment]
The issue tracker is for bugs and feature requests. Not for (albeit related) support requests. I cannot possibly answer every support request for various network issues/questions.

Please use the "Discussions" tab in this repository instead. Feel free to expand the wiki with clearer instructions once you figure things out.
