### ISSUE TITLE
[Feature Request]: Can this integration work with Home Assistant - Modbus Proxy ???

### ISSUE THREAD

**Issue by Infernoken76** [wlcrs/huawei_solar#843]
### Describe your feature request

As I have 2 devices that need to pull data from my Huawei invertor  (Home Assistant and a EMS (Energy Management System), I would like to work with a ModBus proxy to allow communication from both to the inverter:

https://github.com/Akulatraxas/ha-modbusproxy

This means that I would like this Huawei integration to use the ModBus proxy address of the same machine where Home Assistant is running...

Any idea if this is feasible with the current implementation?

### Proper usage

- [X] I confirm that this is not a bug report or support request
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by wlcrs** [comment]
I don't provide any support whatsoever for usage with 3rd party software.
