### ISSUE TITLE
[Bug]: The Modbus Proxy recommended in the Q&A section seems not to work with Huawei_Solar

### ISSUE THREAD

**Issue by Erkessolar** [wlcrs/huawei_solar#853]
### Describe the issue

The Modbus proxy configuration does not allow to add the slave ID "0"
connection was made through the Sun200 internal wifi.

### Describe your Huawei Solar Setup

Inverter Type: 
Inverter Firmware version: 
sDongle present: Yes / No
sDongle Type: sDongleA-05 (WiFi / Ethernet) / SDongleA-03 (4G)
sDongle Connectivitiy: WiFi / Ethernet / 4G
sDongle Firmware: 
Power meter present: three phase / single phase / no
Optimizers Present: Yes / No
Battery: LUNA2000-SO xxkWh / LUNA2000-S1 xxkWh (Released 2024) / LG RESU xxkWh / None
Battery Firmware version: 
Huawei Solar integration version: 

### How do you connect to the inverter?

Please select your connection method

### Upload your Diagnostics File

Drag & Drop your Diagnostics File here.

### Upload your relevant debug logs

```text
huawei_solar
can't connect to the Modbus Proxy.
```

### Please confirm the following:

- [X] I'm running the latest release of Home Assistant.
- [ ] I'm running the latest release of this integration.
- [ ] I did not find an existing issue describing this problem.
- [ ] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [ ] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by Retony79** [comment]
good morning everyone, I'm new to the forum and to home assistant. Since yesterday, Huawei Solar no longer works well after the latest update of Huawei V200R001C00SPC144. Do you have a solution? Thank you very much and I apologize if I did something wrong

**Comment by wlcrs** [comment]
I don't provide support for 3rd party software.
