### ISSUE TITLE
[Bug]: Error occurred loading flow for integration huawei_solar: cannot import name 'ModbusRequest' from 'pymodbus.pdu' (/usr/local/lib/python3.12/site-packages/pymodbus/pdu/__init__.py)

### ISSUE THREAD

**Issue by Lk1975** [wlcrs/huawei_solar#866]
### Describe the issue

Installed integration for the first time in last stable version, and gives error "setup failed for custom integration 'huawei_solar': Unable to import component: No module named 'pymodbus.message'". Tried to uninstall and install using beta version and gives the error in the object. I have another integration using modbus, [koolnova-BMS-Integration](https://github.com/sinseman44/koolnova-BMS-Integration) that is working fine with a separate dongle.

### Describe your Huawei Solar Setup

Inverter Type: 
Inverter Firmware version: 
sDongle present: Yes / No
sDongle Type: sDongleA-05 (WiFi / Ethernet) / SDongleA-03 (4G)
sDongle Connectivitiy: WiFi / Ethernet / 4G
sDongle Firmware: 
Power meter present: three phase / single phase / no
Optimizers Present: Yes / No
Battery: LUNA2000-SO xxkWh / LUNA2000-S1 xxkWh (Released 2024) / LG RESU xxkWh / None
Battery Firmware version: 
Huawei Solar integration version: 

### How do you connect to the inverter?

Over serial, with a serial-to-USB stick

### Upload your Diagnostics File

Drag & Drop your Diagnostics File here.

### Upload your relevant debug logs

```text
Registratore: homeassistant.config_entries
Fonte: config_entries.py:3249
Prima occorrenza: 21:09:13 (1 occorrenze)
Ultima registrazione: 21:09:13

Error occurred loading flow for integration huawei_solar: No module named 'pymodbus.message'
```

### Please confirm the following:

- [ ] I'm running the latest release of Home Assistant.
- [X] I'm running the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [ ] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [x] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by wlcrs** [comment]
The other integration uses an incompatible version of pymodbus: it requires v3.7.4 while this integration requires 3.6.9 or lower.

This is sadly a limitation of the Python library versioning system on which HA depends. I therefore suggest downgrading the other integration for the time being. 

My policy is that I keep the required version of pymodbus in sync with the native modbus integration of Home assistant. That integration is currently pinning the version of pymodbus to v3.6.9 too for the moment. 

I expect that the author of pymodbus will bump the version required by the native modbus integration to v3.8 or higher when that update happens, as that version has been released this weekend. I will thus never release a v3.7.x compatible version of this integration.
