### ISSUE TITLE
[Feature Request]: How to build a power flow card

### ISSUE THREAD

**Issue by EmAnzi3** [wlcrs/huawei_solar#89]
### Describe your feature request

Hello,
First of all many thanks for this helpful integration, it works like a charm in the HA Energy tab.
However, I was searching for a solution to replicate in HA a power flow card like the one of FusionSolar app.
My setup is a bit articulated since I have 2 inverters and 3 batteries and I'm a bit lost with parameter to be used and summed together.
Thanks in advance for your kind support.

![Immagine 2022-07-17 102540](https://user-images.githubusercontent.com/27973961/179390314-8084a77d-897c-4ae8-97b9-18c222cc3856.png)

**Comment by wlcrs** [comment]
This is out of scope for the issue tracker. Please use an other channel instead (for example the Discussions tab)
