### ISSUE TITLE
[Bug]: Optimizer Temp last and first value between idle is sometimes 0

### ISSUE THREAD

**Issue by luzik** [wlcrs/huawei_solar#96]
### System Health details

All up to date, and not releted

### Huawei Solar Setup

5ktl-m1 + SDongle via Ethernet

### Describe the issue

Sometimes when device is going to idle state and returning back, optimizer temp is reported as 0 - this is not true

![image](https://user-images.githubusercontent.com/6113774/180949916-42e3e962-ce5f-41ef-be2b-7400ac4bff08.png)

and its look ugly on statistics cards

### Reproduction steps

1. Graph Optimizer temp

### Relevant debug logs

```text
XXX
```

**Comment by wlcrs** [comment]
I'm going to test the fix locally before doing a bugfix release. As the optimizers need to go offline at night, we need to be a bit patient to test this.
