### ISSUE TITLE
[Feature Request]: Optimizer naming convention

### ISSUE THREAD

**Issue by luzik** [wlcrs/huawei_solar#97]
### Describe your feature request

Fusion Solar is using optimizer names as number in DC chain
1.1.1
1.1.2
1.1.3 and so on
Now names are defaults to SN, and it is hard to find one you want to find.
If 1.X.X is not avaiable via modbus, then it should be possible to discover this index using "Voltage to ground" - as every PV have higher voltage to the ground. This is how FusionSolar calculate its index (number in chain)

BTW look how great it looks! I have few PV facing SE and few with azimuth SW. Awesome update!
![image](https://user-images.githubusercontent.com/6113774/180949458-fec14884-6f38-44ea-87f0-88b94ac9330d.png)

**Comment by wlcrs** [comment]
> If 1.X.X is not avaiable via modbus, then it should be possible to discover this index using "Voltage to ground" - as every PV have higher voltage to the ground. This is how FusionSolar calculate its index (number in chain)

Do you have a source for that?

**Comment by luzik** [comment]
No, but this is the only way it can be done as every optimizer can only speak for themself and voltage to ground is something it can measure because it is connected to grounded frame

**Comment by luzik** [comment]
I believe that second chain is using 1.2.X naming, but someone should confirm this.

**Comment by wlcrs** [comment]
While it would be nice to have a consistent naming with FusionSolar, it is not easily doable: the `voltage_to_ground` will be unavailable when the integration is initialized when its dark outside. 

I will therefore not pursue this any further, but I'm open to review PR's for this functionality.
